export const ROUTES = {
  login: "/login",
  dashboard: "/dashboard",
  register: "/register",
  patientDetail: (id: number | string) => `/patients/detail?id=${id}`,
  terms: "/terms",
  identity: "/profile/identity",
  serviceAreas: "/profile/service-areas",
  experience: "/profile/experience",
  skills: "/profile/skills",
  patientNotes: "/patient-notes",
  references: "/profile/references",
  history: "/history",
  serviceHistory: "/service-history",
  blacklistAppeal: "/blacklist-appeal",
  myProfile: "/my-profile",
  familyView: "/my-profile/family-view",
}
