# Generated by Django 6.0.6 on 2026-07-05 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_platformsettings'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(blank=True, help_text='در صورتی که این تراکنش مربوط به خرید از یک فروشگاه باشد', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.order'),
        ),
    ]
