# Generated by Django 5.2.17 on 2026-09-26 12:58

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agencies", "0008_agencyadmin_position_agencysupervisor_position"),
    ]

    operations = [
        migrations.CreateModel(
            name="StageTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pipeline_key", models.CharField(db_index=True, max_length=40)),
                ("object_id", models.PositiveIntegerField(db_index=True)),
                ("to_value", models.CharField(db_index=True, max_length=40)),
                (
                    "changed_at",
                    django_jalali.db.models.jDateTimeField(auto_now_add=True),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
                "indexes": [
                    models.Index(
                        fields=["pipeline_key", "object_id", "to_value"],
                        name="reminders_s_pipelin_72b0ea_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReminderRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pipeline_key", models.CharField(db_index=True, max_length=40)),
                ("anchor_stage", models.CharField(max_length=40)),
                ("display_stage", models.CharField(max_length=40)),
                ("days_threshold", models.PositiveIntegerField(default=7)),
                ("label", models.CharField(max_length=150)),
                (
                    "color",
                    models.CharField(
                        choices=[("red", "قرمز"), ("amber", "نارنجی"), ("blue", "آبی")],
                        default="red",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_at",
                    django_jalali.db.models.jDateTimeField(auto_now_add=True),
                ),
                ("updated_at", django_jalali.db.models.jDateTimeField(auto_now=True)),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder_rules",
                        to="agencies.agencyprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["pipeline_key", "days_threshold"],
                "indexes": [
                    models.Index(
                        fields=["agency", "pipeline_key", "is_active"],
                        name="reminders_r_agency__762a1e_idx",
                    )
                ],
            },
        ),
    ]
