# Generated by Django 6.0.7 on 2026-08-01 06:46

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(db_index=True, help_text='شناسه کاربری در سرویس هویت', unique=True)),
                ('display_name', models.CharField(help_text='نام نمایشی', max_length=150)),
                ('city', models.CharField(blank=True, help_text='شهر', max_length=100)),
                ('address', models.TextField(blank=True, help_text='نشانی')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ و زمان بروزرسانی')),
            ],
            options={
                'verbose_name': 'پروفایل خانواده',
                'verbose_name_plural': 'پروفایل\u200cهای خانواده',
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('full_name', models.CharField(help_text='نام و نام خانوادگی سالمند', max_length=150)),
                ('father_name', models.CharField(blank=True, help_text='نام پدر', max_length=150)),
                ('birth_date', django_jalali.db.models.jDateField(blank=True, help_text='تاریخ تولد', null=True)),
                ('national_id', models.CharField(blank=True, help_text='شماره ملی', max_length=10)),
                ('birth_certificate_number', models.CharField(blank=True, help_text='شماره شناسنامه', max_length=30)),
                ('birth_certificate_issue_place', models.CharField(blank=True, help_text='محل صدور شناسنامه', max_length=150)),
                ('full_address', models.TextField(blank=True, help_text='نشانی کامل محل سکونت (شهر، خیابان، پلاک، واحد)')),
                ('postal_code', models.CharField(blank=True, help_text='کد پستی', max_length=10)),
                ('emergency_contact_phone', models.CharField(blank=True, help_text='شماره تماس اضطراری یکی از اعضای خانواده یا سرپرست', max_length=15)),
                ('guardianship_status', models.CharField(choices=[('none', 'ندارد'), ('legal_guardian', 'قیم قانونی دارد'), ('trustee', 'وصی دارد')], default='none', help_text='وضعیت حقوقی/سرپرستی — آیا وصی یا قیم قانونی دارد؟', max_length=20)),
                ('guardian_details', models.TextField(blank=True, help_text='نام/اطلاعات تماس وصی یا قیم قانونی، در صورت وجود')),
                ('language_dialect', models.CharField(blank=True, help_text='زبان و گویش', max_length=100)),
                ('basic_medical_info', models.TextField(blank=True, help_text='اطلاعات پزشکی پایه — بیماری\u200cهای مهم و نیازهای ویژه')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ و زمان بروزرسانی')),
            ],
            options={
                'verbose_name': 'پروفایل بیمار',
                'verbose_name_plural': 'پروفایل\u200cهای بیمار',
            },
        ),
        migrations.CreateModel(
            name='PatientCompatibilityQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('religious_beliefs_priority', models.CharField(choices=[('strongly_agree', 'کاملاً موافقم'), ('somewhat_agree', 'تاحدی موافق'), ('somewhat_disagree', 'تاحدی مخالف'), ('strongly_disagree', 'کاملاً مخالف')], max_length=20, verbose_name='اهمیت باورهای دینی')),
                ('new_treatment_openness', models.CharField(choices=[('very_high', 'خیلی زیاد'), ('moderate', 'نسبتاً'), ('low', 'کم'), ('none', 'اصلاً')], max_length=20, verbose_name='باز بودن به درمان جدید')),
                ('caregiver_as_family_member', models.CharField(choices=[('yes', 'بله'), ('no', 'خیر'), ('partially', 'تاحدی')], max_length=20, verbose_name='مراقب به عنوان عضو خانواده')),
                ('respectful_disagreement_acceptance', models.CharField(choices=[('fully_accept', 'کاملاً می\u200cپذیرم'), ('mostly_accept', 'نسبتاً می\u200cپذیرم'), ('reluctantly_accept', 'به سختی می\u200cپذیرم'), ('reject', 'قطعاً رد می\u200cکنم')], max_length=20, verbose_name='پذیرش نظرات مخالف با احترام')),
                ('privacy_comfort_with_caregiver', models.CharField(choices=[('yes', 'بله'), ('no', 'خیر'), ('partially', 'تاحدی')], max_length=20, verbose_name='راحتی در حضور مراقب')),
                ('noise_smell_sensitivity', models.CharField(choices=[('very_high', 'خیلی زیاد'), ('moderate', 'نسبتاً'), ('low', 'کم'), ('none', 'اصلاً')], max_length=20, verbose_name='حساسیت به صدا و بو')),
                ('meal_time_strictness', models.CharField(choices=[('very_high', 'خیلی زیاد'), ('moderate', 'نسبتاً'), ('low', 'کم'), ('none', 'اصلاً')], help_text='⚠️ گزینه\u200cهای دقیق در سند منبع مشخص نشده بود — placeholder، نیاز به تأیید محصول', max_length=20, verbose_name='سختی در رعایت زمان وعده غذایی')),
                ('special_diet_preference', models.CharField(choices=[('yes', 'بله'), ('no', 'خیر'), ('partially', 'تاحدی')], max_length=20, verbose_name='ترجیح داشتن رژیم خاص')),
                ('medication_timing_priority', models.CharField(choices=[('very_high', 'خیلی زیاد'), ('moderate', 'نسبتاً'), ('low', 'کم'), ('none', 'اصلاً')], help_text='⚠️ گزینه\u200cهای دقیق در سند منبع مشخص نشده بود — placeholder، نیاز به تأیید محصول', max_length=20, verbose_name='اهمیت زمان\u200cبندی داروها')),
                ('accent_customs_annoyance', models.CharField(choices=[('not_at_all', 'اصلاً'), ('slightly', 'کمی'), ('a_lot', 'زیاد'), ('very_much', 'خیلی زیاد')], max_length=20, verbose_name='آزردگی از لهجه یا رسوم متفاوت مراقب')),
                ('cultural_respect_expectation', models.CharField(choices=[('yes', 'بله'), ('no', 'خیر'), ('partially', 'تاحدی')], max_length=20, verbose_name='انتظار احترام فرهنگی')),
                ('willingness_to_express_opinion', models.CharField(choices=[('very_high', 'خیلی زیاد'), ('moderate', 'نسبتاً'), ('low', 'کم'), ('none', 'اصلاً')], help_text='⚠️ گزینه\u200cهای دقیق در سند منبع مشخص نشده بود — placeholder، نیاز به تأیید محصول', max_length=20, verbose_name='آمادگی برای بیان نظر')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ و زمان بروزرسانی')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_questionnaire', to='families.patientprofile', verbose_name='سالمند')),
            ],
            options={
                'verbose_name': 'پرسشنامه سازگاری بیمار',
                'verbose_name_plural': 'پرسشنامه\u200cهای سازگاری بیمار',
            },
        ),
        migrations.CreateModel(
            name='FamilyPatientLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(help_text='نسبت، مثلاً فرزند/همسر/سرپرست', max_length=50)),
                ('is_primary_contact', models.BooleanField(default=True)),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ و زمان بروزرسانی')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_links', to='families.familyprofile', verbose_name='خانواده')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_links', to='families.patientprofile', verbose_name='سالمند')),
            ],
            options={
                'verbose_name': 'ارتباط خانواده و بیمار',
                'verbose_name_plural': 'ارتباط\u200cهای خانواده و بیمار',
                'unique_together': {('family', 'patient')},
            },
        ),
    ]
