# Generated by Django 6.0.7 on 2026-07-31 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familypatientlink',
            options={'verbose_name': 'ارتباط خانواده و بیمار', 'verbose_name_plural': 'ارتباط\u200cهای خانواده و بیمار'},
        ),
        migrations.AlterModelOptions(
            name='familyprofile',
            options={'verbose_name': 'پروفایل خانواده', 'verbose_name_plural': 'پروفایل\u200cهای خانواده'},
        ),
        migrations.AlterModelOptions(
            name='patientcompatibilityquestionnaire',
            options={'verbose_name': 'پرسشنامه سازگاری بیمار', 'verbose_name_plural': 'پرسشنامه\u200cهای سازگاری بیمار'},
        ),
        migrations.AlterModelOptions(
            name='patientprofile',
            options={'verbose_name': 'پروفایل بیمار', 'verbose_name_plural': 'پروفایل\u200cهای بیمار'},
        ),
        migrations.AddField(
            model_name='familypatientlink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ و زمان بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='familypatientlink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='familypatientlink',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_links', to='families.familyprofile', verbose_name='خانواده'),
        ),
        migrations.AlterField(
            model_name='familypatientlink',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_links', to='families.patientprofile', verbose_name='سالمند'),
        ),
        migrations.AlterField(
            model_name='familyprofile',
            name='address',
            field=models.TextField(blank=True, help_text='نشانی'),
        ),
        migrations.AlterField(
            model_name='familyprofile',
            name='city',
            field=models.CharField(blank=True, help_text='شهر', max_length=100),
        ),
        migrations.AlterField(
            model_name='familyprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='familyprofile',
            name='display_name',
            field=models.CharField(help_text='نام نمایشی', max_length=150),
        ),
        migrations.AlterField(
            model_name='familyprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ و زمان بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='familyprofile',
            name='user_id',
            field=models.PositiveIntegerField(db_index=True, help_text='شناسه کاربری در سرویس هویت', unique=True),
        ),
        migrations.AlterField(
            model_name='patientcompatibilityquestionnaire',
            name='accent_customs_annoyance',
            field=models.CharField(choices=[('not_at_all', 'اصلاً'), ('slightly', 'کمی'), ('a_lot', 'زیاد'), ('very_much', 'خیلی زیاد')], max_length=20, verbose_name='آزردگی از لهجه یا رسوم متفاوت مراقب'),
        ),
        migrations.AlterField(
            model_name='patientcompatibilityquestionnaire',
            name='caregiver_as_family_member',
            field=models.CharField(choices=[('yes', 'بله'), ('no', 'خیر'), ('partially', 'تاحدی')], max_length=20, verbose_name='مراقب به عنوان عضو خانواده'),
        ),
        migrations.AlterField(
            model_name='patientcompatibilityquestionnaire',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='patientcompatibilityquestionnaire',
            name='cultural_respect_expectation',
            field=models.CharField(choices=[('yes', 'بله'), ('no', 'خیر'), ('partially', 'تاحدی')], max_length=20, verbose_name='انتظار احترام فرهنگی'),
        ),
        migrations.AlterField(
            model_name='patientcompatibilityquestionnaire',
            name='meal_time_strictness',
            field=models.CharField(choices=[('very_high', 'خیلی زیاد'), ('moderate', 'نسبتاً'), ('low', 'کم'), ('none', 'اصلاً')], help_text='⚠️ گزینه\u200cهای دقیق در سند منبع مشخص نشده بود — placeholder، نیاز به تأیید محصول', max_length=20, verbose_name='سختی در رعایت زمان وعده غذایی'),
        ),
        migrations.AlterField(
            model_name='patientcompatibilityquestionnaire',
            name='medication_timing_priority',
            field=models.CharField(choices=[('very_high', 'خیلی زیاد'), ('moderate', 'نسبتاً'), ('low', 'کم'), ('none', 'اصلاً')], help_text='⚠️ گزینه\u200cهای دقیق در سند منبع مشخص نشده بود — placeholder، نیاز به تأیید محصول', max_length=20, verbose_name='اهمیت زمان\u200cبندی داروها'),
        ),
        migrations.AlterField(
            model_name='patientcompatibilityquestionnaire',
            name='new_treatment_openness',
            field=models.CharField(choices=[('very_high', 'خیلی زیاد'), ('moderate', 'نسبتاً'), ('low', 'کم'), ('none', 'اصلاً')], max_length=20, verbose_name='باز بودن به درمان جدید'),
        ),
        migrations.AlterField(
            model_name='patientcompatibilityquestionnaire',
            name='noise_smell_sensitivity',
            field=models.CharField(choices=[('very_high', 'خیلی زیاد'), ('moderate', 'نسبتاً'), ('low', 'کم'), ('none', 'اصلاً')], max_length=20, verbose_name='حساسیت به صدا و بو'),
        ),
        migrations.AlterField(
            model_name='patientcompatibilityquestionnaire',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_questionnaire', to='families.patientprofile', verbose_name='سالمند'),
        ),
        migrations.AlterField(
            model_name='patientcompatibilityquestionnaire',
            name='privacy_comfort_with_caregiver',
            field=models.CharField(choices=[('yes', 'بله'), ('no', 'خیر'), ('partially', 'تاحدی')], max_length=20, verbose_name='راحتی در حضور مراقب'),
        ),
        migrations.AlterField(
            model_name='patientcompatibilityquestionnaire',
            name='religious_beliefs_priority',
            field=models.CharField(choices=[('strongly_agree', 'کاملاً موافقم'), ('somewhat_agree', 'تاحدی موافق'), ('somewhat_disagree', 'تاحدی مخالف'), ('strongly_disagree', 'کاملاً مخالف')], max_length=20, verbose_name='اهمیت باورهای دینی'),
        ),
        migrations.AlterField(
            model_name='patientcompatibilityquestionnaire',
            name='respectful_disagreement_acceptance',
            field=models.CharField(choices=[('fully_accept', 'کاملاً می\u200cپذیرم'), ('mostly_accept', 'نسبتاً می\u200cپذیرم'), ('reluctantly_accept', 'به سختی می\u200cپذیرم'), ('reject', 'قطعاً رد می\u200cکنم')], max_length=20, verbose_name='پذیرش نظرات مخالف با احترام'),
        ),
        migrations.AlterField(
            model_name='patientcompatibilityquestionnaire',
            name='special_diet_preference',
            field=models.CharField(choices=[('yes', 'بله'), ('no', 'خیر'), ('partially', 'تاحدی')], max_length=20, verbose_name='ترجیح داشتن رژیم خاص'),
        ),
        migrations.AlterField(
            model_name='patientcompatibilityquestionnaire',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ و زمان بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='patientcompatibilityquestionnaire',
            name='willingness_to_express_opinion',
            field=models.CharField(choices=[('very_high', 'خیلی زیاد'), ('moderate', 'نسبتاً'), ('low', 'کم'), ('none', 'اصلاً')], help_text='⚠️ گزینه\u200cهای دقیق در سند منبع مشخص نشده بود — placeholder، نیاز به تأیید محصول', max_length=20, verbose_name='آمادگی برای بیان نظر'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='birth_date',
            field=models.DateField(blank=True, help_text='تاریخ تولد', null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='postal_code',
            field=models.CharField(blank=True, help_text='کد پستی', max_length=10),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ و زمان بروزرسانی'),
        ),
    ]
