# Generated by Django 6.0.7 on 2026-08-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0005_access_codes_and_link_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familypatientlink',
            name='relation',
            field=models.CharField(choices=[('child', 'فرزند'), ('spouse', 'همسر'), ('father', 'پدر'), ('mother', 'مادر'), ('sibling', 'خواهر / برادر'), ('grandchild', 'نوه'), ('other', 'سایر')], default='other', help_text='نسبت', max_length=50),
        ),
        migrations.AlterField(
            model_name='familyprofile',
            name='display_name',
            field=models.CharField(blank=True, help_text='نام نمایشی', max_length=150),
        ),
    ]
