# Generated by Django 6.0.7 on 2026-08-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0006_alter_familypatientlink_relation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'زن'), ('male', 'مرد')], help_text='جنسیت', max_length=10),
        ),
    ]
