# Generated by Django 6.0.7 on 2026-08-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0007_patientprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcompatibilityquestionnaire',
            name='meal_time_strictness',
            field=models.CharField(
                choices=[
                    ('very_strict', 'بسیار مهم است و باید دقیقاً رعایت شود'),
                    ('moderately_strict', 'نسبتاً مهم است، کمی تأخیر قابل قبول است'),
                    ('flexible', 'چندان مهم نیست، انعطاف‌پذیر است'),
                    ('not_important', 'اهمیتی ندارد'),
                ],
                max_length=20,
                verbose_name='سختی در رعایت زمان وعده غذایی',
            ),
        ),
        migrations.AlterField(
            model_name='patientcompatibilityquestionnaire',
            name='medication_timing_priority',
            field=models.CharField(
                choices=[
                    ('very_strict', 'بسیار مهم است و باید دقیقاً رعایت شود'),
                    ('moderately_strict', 'نسبتاً مهم است، کمی تأخیر قابل قبول است'),
                    ('flexible', 'چندان مهم نیست، انعطاف‌پذیر است'),
                    ('not_important', 'اهمیتی ندارد'),
                ],
                max_length=20,
                verbose_name='اهمیت زمان‌بندی داروها',
            ),
        ),
        migrations.AlterField(
            model_name='patientcompatibilityquestionnaire',
            name='willingness_to_express_opinion',
            field=models.CharField(
                choices=[
                    ('very_willing', 'همیشه نظر خود را بیان می‌کند'),
                    ('somewhat_willing', 'بیشتر مواقع نظر خود را می‌گوید'),
                    ('rarely_willing', 'به‌ندرت نظر خود را بیان می‌کند'),
                    ('not_willing', 'تمایلی به بیان نظر ندارد'),
                ],
                max_length=20,
                verbose_name='آمادگی برای بیان نظر',
            ),
        ),
    ]
