# Generated by Django 6.0.7 on 2026-08-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0008_resolve_questionnaire_placeholder_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='physical_condition',
            field=models.CharField(
                blank=True,
                choices=[
                    ('independent', 'سالمند مستقل'),
                    ('low_mobility', 'سالمند کم‌توان (همراهی در راه رفتن)'),
                    ('limited_mobility_bedridden', 'سالمند دارای محدودیت حرکتی (روی تخت)'),
                    ('bedridden_diaper', 'سالمند بستری در منزل (پوشکی)'),
                    ('alzheimers', 'سالمند مبتلا به آلزایمر'),
                    ('parkinsons', 'سالمند مبتلا به پارکینسون'),
                    ('hospital_companion_needed', 'سالمند نیازمند همراهی بیمارستانی'),
                ],
                help_text='شرایط جسمانی فعلی سالمند — برای تطبیق با تخصص مراقب در سیستم تطبیق',
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='needed_shifts',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='شیفت‌های زمانی مورد نیاز برای مراقبت (چندانتخابی از NeededShift)',
            ),
        ),
    ]
