# Generated by Django 6.0.7 on 2026-09-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("families", "0009_patient_care_needs"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="pipeline_status",
            field=models.CharField(
                choices=[
                    ("registration", "ثبت\u200cنام ورود"),
                    ("phone_coordination", "هماهنگی تلفنی"),
                    ("dispatched", "اعزام"),
                    ("caregiver_confirmed", "تایید پرستار"),
                    ("first_week_followup", "هفته اول: پیگیری اولیه"),
                    ("contract_confirmed", "قرارداد بسته و تایید شده"),
                    ("expired", "منقضی\u200cها"),
                ],
                db_index=True,
                default="registration",
                max_length=30,
                verbose_name="مرحله کاریز خدمت",
            ),
        ),
    ]
