# Generated by Django 6.0.7 on 2026-09-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("families", "0010_patientprofile_pipeline_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="is_urgent",
            field=models.BooleanField(
                default=False,
                help_text="برچسب فوری روی کارت این خدمت\u200cگیرنده در کاریز آژانس نمایش داده می\u200cشود.",
                verbose_name="فوری",
            ),
        ),
    ]
