# Generated by Django 6.0.7 on 2026-09-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("families", "0011_patientprofile_is_urgent"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="برچسب\u200cهای آزاد آژانس روی این خدمت\u200cگیرنده، برای دسته\u200cبندی و فیلتر آینده کاریز.",
                verbose_name="برچسب\u200cها",
            ),
        ),
    ]
