# Generated by Django 5.2.17 on 2026-09-28 11:31

import apps.families.models
import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("families", "0012_patientprofile_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientDocumentUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("national_id_card", "کارت ملی"),
                            ("birth_certificate", "شناسنامه"),
                            ("personal_photo", "عکس پرسنلی"),
                        ],
                        max_length=30,
                        verbose_name="نوع مدرک",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.families.models.patient_document_upload_path,
                        verbose_name="فایل",
                    ),
                ),
                (
                    "uploaded_at",
                    django_jalali.db.models.jDateTimeField(
                        auto_now=True, verbose_name="زمان بارگذاری"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_uploads",
                        to="families.patientprofile",
                        verbose_name="سالمند",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patient_documents_uploaded",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="بارگذاری\u200cکننده",
                    ),
                ),
            ],
            options={
                "verbose_name": "مدرک هویتی سالمند",
                "verbose_name_plural": "مدارک هویتی سالمند",
                "unique_together": {("patient", "document_type")},
            },
        ),
    ]
