# Generated by Django 5.2.17 on 2026-09-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("families", "0013_patientdocumentupload"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="یادداشت آزاد کارکنان آژانس روی کارت این خدمت\u200cگیرنده در کاریز — فقط داخلی، برای نمایش عمومی نیست.",
                verbose_name="یادداشت داخلی",
            ),
        ),
    ]
