# Generated by Django 5.2.17 on 2026-09-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("families", "0014_patientprofile_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientprofile",
            name="pipeline_status",
            field=models.CharField(
                db_index=True,
                default="registration",
                max_length=30,
                verbose_name="مرحله کاریز خدمت",
            ),
        ),
    ]
