# Generated by Django 5.2.17 on 2026-09-30 06:13

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("families", "0015_alter_patientprofile_pipeline_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="contract_end_date",
            field=django_jalali.db.models.jDateField(
                blank=True,
                help_text="تاریخ پایان قرارداد فعلی این خدمت\u200cگیرنده — کنار تاریخ شروع، برای پیگیری نزدیک\u200cشدن به پایان قرارداد.",
                null=True,
                verbose_name="تاریخ پایان قرارداد فعلی",
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="contract_start_date",
            field=django_jalali.db.models.jDateField(
                blank=True,
                help_text="تاریخ شروع قرارداد فعلی این خدمت\u200cگیرنده — در مرحله «قرارداد بسته و تایید شده» ثبت می\u200cشود.",
                null=True,
                verbose_name="تاریخ شروع قرارداد فعلی",
            ),
        ),
    ]
