# Generated by Django 5.2.17 on 2026-10-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("families", "0016_patientprofile_contract_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="service_subtype",
            field=models.CharField(
                blank=True,
                default="",
                help_text="مثلاً newborn / child برای مادریار، یا inside_home برای امور منزل.",
                max_length=30,
                verbose_name="زیرشاخه\u200cی خدمت",
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="service_type",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="کلیدی از apps.caregivers.choices.ServiceType؛ خالی برای رکوردهای قدیمی.",
                max_length=20,
                verbose_name="نوع خدمت مورد نیاز",
            ),
        ),
        migrations.AlterField(
            model_name="patientprofile",
            name="full_name",
            field=models.CharField(
                help_text="نام و نام خانوادگی خدمت\u200cگیرنده", max_length=150
            ),
        ),
    ]
