# Generated by Django 5.2.17 on 2026-10-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("families", "0017_patient_service_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="ethnicities",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="قومیت / زبان مادری — کلیدهای caregivers.choices.Ethnicity",
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="ethnicity_details",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="اهل کجا — زیرگروه هر قومیت (ETHNICITY_SUBGROUPS)",
            ),
        ),
        migrations.AlterField(
            model_name="patientprofile",
            name="language_dialect",
            field=models.CharField(
                blank=True,
                help_text="زبان و گویش (قدیمی؛ جایگزین: ethnicities)",
                max_length=100,
            ),
        ),
    ]
