# Generated by Django 6.0.7 on 2026-07-31 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_by_user_id', models.PositiveIntegerField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaregiverExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elderly_care_experience', models.CharField(choices=[('none', 'ندارم'), ('under_1_year', 'کمتر از ۱ سال'), ('1_to_5_years', 'بین ۱ تا ۵ سال'), ('over_5_years', 'بیش از ۵ سال')], max_length=20)),
                ('other_services_experience', models.CharField(blank=True, choices=[('none', 'ندارم'), ('under_1_year', 'کمتر از ۱ سال'), ('1_to_5_years', 'بین ۱ تا ۵ سال'), ('over_5_years', 'بیش از ۵ سال')], max_length=20)),
                ('previous_workplaces', models.JSONField(blank=True, default=list, help_text='چندانتخابی')),
                ('patients_cared_for_count', models.CharField(blank=True, choices=[('one', '۱ نفر'), ('2_to_5', '۲ تا ۵ نفر'), ('6_to_10', '۶ تا ۱۰ نفر'), ('11_to_20', '۱۱ تا ۲۰ نفر'), ('over_20', 'بیش از ۲۰ نفر')], max_length=20)),
                ('special_conditions_experience', models.JSONField(blank=True, default=list, help_text='چندانتخابی')),
                ('live_in_experience', models.BooleanField(blank=True, null=True)),
                ('couple_care_experience', models.BooleanField(blank=True, null=True)),
                ('solo_elderly_care_experience', models.BooleanField(blank=True, null=True)),
                ('driving_for_patient_experience', models.BooleanField(blank=True, null=True)),
                ('last_workplace', models.CharField(blank=True, max_length=200)),
                ('additional_notes', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='caregivers.caregiverprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CaregiverReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('occupation', models.CharField(max_length=150)),
                ('relation_type', models.CharField(choices=[('family', 'خانواده'), ('friends', 'دوستان'), ('former_colleague', 'همکار سابق'), ('trusted_acquaintance', 'آشنای مورد اعتماد')], max_length=30)),
                ('acquaintance_duration', models.CharField(blank=True, choices=[('under_1_year', 'کمتر از ۱ سال'), ('1_to_5_years', 'بین ۱ تا ۵ سال'), ('over_5_years', 'بیش از ۵ سال (مدت زمان زیادی)')], max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('callable_for_inquiry', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='caregivers.caregiverprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CaregiverSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(choices=[('under_diploma', 'زیر دیپلم'), ('diploma', 'دیپلم'), ('associate', 'کاردانی'), ('bachelor', 'کارشناسی'), ('master', 'کارشناسی ارشد'), ('phd', 'دکتری')], max_length=20)),
                ('field_of_study', models.CharField(blank=True, max_length=150)),
                ('training_courses', models.JSONField(blank=True, default=list, help_text='چندانتخابی')),
                ('communication_skills', models.JSONField(blank=True, default=list, help_text='چندانتخابی')),
                ('caregiving_skills', models.JSONField(blank=True, default=list, help_text='چندانتخابی')),
                ('physical_ability', models.CharField(blank=True, choices=[('weak', 'ضعیف'), ('moderate', 'متوسط'), ('good', 'خوب'), ('very_good', 'بسیار خوب')], max_length=20)),
                ('mobility_assistance_ability', models.JSONField(blank=True, default=list, help_text='چندانتخابی')),
                ('household_skills', models.JSONField(blank=True, default=list, help_text='چندانتخابی')),
                ('foreign_languages', models.JSONField(blank=True, default=list, help_text='چندانتخابی')),
                ('local_languages', models.JSONField(blank=True, default=list, help_text='چندانتخابی')),
                ('has_driving_license', models.BooleanField(blank=True, null=True)),
                ('has_personal_car', models.BooleanField(blank=True, null=True)),
                ('can_use_smartphone', models.BooleanField(blank=True, null=True)),
                ('preferred_messaging_apps', models.JSONField(blank=True, default=list, help_text='چندانتخابی')),
                ('additional_notes', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='caregivers.caregiverprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CaregiverWorkPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaboration_types', models.JSONField(default=list, help_text='چندانتخابی — لیستی از CollaborationType')),
                ('work_status', models.CharField(choices=[('full_time', 'تمام\u200cوقت'), ('part_time', 'پاره\u200cوقت'), ('both', 'هر دو مورد')], max_length=20)),
                ('family_presence_preference', models.CharField(choices=[('prefer_present', 'ترجیح می\u200cدهم عضوی از خانواده در منزل حضور داشته باشد'), ('prefer_absent', 'ترجیح می\u200cدهم خانواده در ساعات کاری خارج از منزل باشند'), ('no_preference', 'برایم اولویت ندارد')], max_length=20)),
                ('accepted_gender', models.CharField(choices=[('female_only', 'فقط خانم'), ('male_only', 'فقط آقا'), ('no_preference', 'تفاوتی ندارد')], max_length=20)),
                ('accepted_age_ranges', models.JSONField(default=list, help_text='چندانتخابی — لیستی از AcceptedAgeRange')),
                ('offered_services', models.JSONField(default=list, help_text='چندانتخابی — لیستی از OfferedService')),
                ('accepted_physical_conditions', models.JSONField(default=list, help_text='چندانتخابی')),
                ('lifting_capacity', models.CharField(choices=[('up_to_30kg', 'تا ۳۰ کیلوگرم'), ('up_to_50kg', 'تا ۵۰ کیلوگرم'), ('over_50kg', 'بیش از ۵۰ کیلوگرم'), ('cannot_lift', 'امکان جابجایی فیزیکی ندارم')], max_length=20)),
                ('service_locations', models.JSONField(default=list, help_text='چندانتخابی — لیستی از ServiceLocation')),
                ('max_commute_time', models.CharField(blank=True, choices=[('up_to_60', 'تا ۶۰ دقیقه'), ('up_to_90', 'تا ۹۰ دقیقه'), ('over_90', 'بیش از ۹۰ دقیقه')], max_length=20)),
                ('available_days', models.JSONField(default=list, help_text='چندانتخابی — لیستی از Weekday')),
                ('available_shifts', models.JSONField(default=list, help_text='چندانتخابی — لیستی از Shift؛ نکته تودرتو در کلاس Shift')),
                ('commute_methods', models.JSONField(blank=True, default=list, help_text='چندانتخابی — لیستی از CommuteMethod')),
                ('smoking_status', models.CharField(blank=True, choices=[('none', 'استعمال نمی\u200cکنم'), ('occasional', 'گهگاه استعمال می\u200cکنم'), ('regular', 'به\u200cصورت منظم استعمال می\u200cکنم')], max_length=20)),
                ('pets_ok', models.BooleanField(blank=True, null=True)),
                ('holiday_work_ok', models.BooleanField(blank=True, null=True)),
                ('overnight_stay_ok', models.BooleanField(blank=True, null=True)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_preferences', to='caregivers.caregiverprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CaregiverServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='caregivers.caregiverprofile')),
            ],
            options={
                'unique_together': {('profile', 'province', 'city', 'district')},
            },
        ),
    ]
