# Generated by Django 6.0.7 on 2026-07-31 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caregiverexperience',
            options={'verbose_name': 'سوابق کاری مراقب', 'verbose_name_plural': 'سوابق کاری مراقبان'},
        ),
        migrations.AlterModelOptions(
            name='caregiverprofile',
            options={'verbose_name': 'پروفایل مراقب', 'verbose_name_plural': 'پروفایل\u200cهای مراقب'},
        ),
        migrations.AlterModelOptions(
            name='caregiverreference',
            options={'verbose_name': 'معرف مراقب', 'verbose_name_plural': 'معرف\u200cهای مراقب'},
        ),
        migrations.AlterModelOptions(
            name='caregiverservicearea',
            options={'verbose_name': 'منطقه خدماتی مراقب', 'verbose_name_plural': 'مناطق خدماتی مراقبان'},
        ),
        migrations.AlterModelOptions(
            name='caregiverskills',
            options={'verbose_name': 'مهارت\u200cهای مراقب', 'verbose_name_plural': 'مهارت\u200cهای مراقبان'},
        ),
        migrations.AlterModelOptions(
            name='caregiverworkpreferences',
            options={'verbose_name': 'شرایط همکاری مراقب', 'verbose_name_plural': 'شرایط همکاری مراقبان'},
        ),
        migrations.AddField(
            model_name='caregiverreference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ و زمان بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='caregiverexperience',
            name='additional_notes',
            field=models.TextField(blank=True, max_length=500, verbose_name='یادداشت\u200cهای اضافی'),
        ),
        migrations.AlterField(
            model_name='caregiverexperience',
            name='couple_care_experience',
            field=models.BooleanField(blank=True, null=True, verbose_name='تجربه مراقبت از زوج'),
        ),
        migrations.AlterField(
            model_name='caregiverexperience',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='caregiverexperience',
            name='driving_for_patient_experience',
            field=models.BooleanField(blank=True, null=True, verbose_name='تجربه رانندگی برای بیمار'),
        ),
        migrations.AlterField(
            model_name='caregiverexperience',
            name='elderly_care_experience',
            field=models.CharField(choices=[('none', 'ندارم'), ('under_1_year', 'کمتر از ۱ سال'), ('1_to_5_years', 'بین ۱ تا ۵ سال'), ('over_5_years', 'بیش از ۵ سال')], max_length=20, verbose_name='تجربه مراقبت از سالمندان'),
        ),
        migrations.AlterField(
            model_name='caregiverexperience',
            name='last_workplace',
            field=models.CharField(blank=True, max_length=200, verbose_name='آخرین محل کار'),
        ),
        migrations.AlterField(
            model_name='caregiverexperience',
            name='live_in_experience',
            field=models.BooleanField(blank=True, null=True, verbose_name='تجربه مراقبت در محل'),
        ),
        migrations.AlterField(
            model_name='caregiverexperience',
            name='other_services_experience',
            field=models.CharField(blank=True, choices=[('none', 'ندارم'), ('under_1_year', 'کمتر از ۱ سال'), ('1_to_5_years', 'بین ۱ تا ۵ سال'), ('over_5_years', 'بیش از ۵ سال')], max_length=20, verbose_name='تجربه خدمات دیگر'),
        ),
        migrations.AlterField(
            model_name='caregiverexperience',
            name='patients_cared_for_count',
            field=models.CharField(blank=True, choices=[('one', '۱ نفر'), ('2_to_5', '۲ تا ۵ نفر'), ('6_to_10', '۶ تا ۱۰ نفر'), ('11_to_20', '۱۱ تا ۲۰ نفر'), ('over_20', 'بیش از ۲۰ نفر')], max_length=20, verbose_name='تعداد بیماران مراقبت شده'),
        ),
        migrations.AlterField(
            model_name='caregiverexperience',
            name='previous_workplaces',
            field=models.JSONField(blank=True, default=list, help_text='چندانتخابی', verbose_name='محلهای پیشین کار'),
        ),
        migrations.AlterField(
            model_name='caregiverexperience',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='caregivers.caregiverprofile', verbose_name='پروفایل مراقب'),
        ),
        migrations.AlterField(
            model_name='caregiverexperience',
            name='solo_elderly_care_experience',
            field=models.BooleanField(blank=True, null=True, verbose_name='تجربه مراقبت تنها از سالمند'),
        ),
        migrations.AlterField(
            model_name='caregiverexperience',
            name='special_conditions_experience',
            field=models.JSONField(blank=True, default=list, help_text='چندانتخابی', verbose_name='تجربه شرایط ویژه'),
        ),
        migrations.AlterField(
            model_name='caregiverexperience',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ و زمان بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='caregiverprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و زمان تأیید'),
        ),
        migrations.AlterField(
            model_name='caregiverprofile',
            name='approved_by_user_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='شناسه کاربر تأییدکننده'),
        ),
        migrations.AlterField(
            model_name='caregiverprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='caregiverprofile',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='تأیید شده'),
        ),
        migrations.AlterField(
            model_name='caregiverprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ و زمان بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='caregiverprofile',
            name='user_id',
            field=models.PositiveIntegerField(db_index=True, unique=True, verbose_name='شناسه کاربر'),
        ),
        migrations.AlterField(
            model_name='caregiverreference',
            name='acquaintance_duration',
            field=models.CharField(blank=True, choices=[('under_1_year', 'کمتر از ۱ سال'), ('1_to_5_years', 'بین ۱ تا ۵ سال'), ('over_5_years', 'بیش از ۵ سال (مدت زمان زیادی)')], max_length=20, verbose_name='مدت آشنایی'),
        ),
        migrations.AlterField(
            model_name='caregiverreference',
            name='callable_for_inquiry',
            field=models.BooleanField(default=True, verbose_name='امکان تماس جهت استعلام'),
        ),
        migrations.AlterField(
            model_name='caregiverreference',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='caregiverreference',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='نام کامل'),
        ),
        migrations.AlterField(
            model_name='caregiverreference',
            name='occupation',
            field=models.CharField(max_length=150, verbose_name='شغل'),
        ),
        migrations.AlterField(
            model_name='caregiverreference',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='caregiverreference',
            name='relation_type',
            field=models.CharField(choices=[('family', 'خانواده'), ('friends', 'دوستان'), ('former_colleague', 'همکار سابق'), ('trusted_acquaintance', 'آشنای مورد اعتماد')], max_length=30, verbose_name='نوع رابطه'),
        ),
        migrations.AlterField(
            model_name='caregiverservicearea',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='caregiverservicearea',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='منطقه'),
        ),
        migrations.AlterField(
            model_name='caregiverservicearea',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='caregivers.caregiverprofile', verbose_name='پروفایل مراقب'),
        ),
        migrations.AlterField(
            model_name='caregiverservicearea',
            name='province',
            field=models.CharField(max_length=100, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='caregiverskills',
            name='additional_notes',
            field=models.TextField(blank=True, max_length=500, verbose_name='یادداشت\u200cهای اضافی'),
        ),
        migrations.AlterField(
            model_name='caregiverskills',
            name='can_use_smartphone',
            field=models.BooleanField(blank=True, null=True, verbose_name='توانایی استفاده از گوشی هوشمند'),
        ),
        migrations.AlterField(
            model_name='caregiverskills',
            name='caregiving_skills',
            field=models.JSONField(blank=True, default=list, help_text='چندانتخابی', verbose_name='مهارت\u200cهای مراقبتی'),
        ),
        migrations.AlterField(
            model_name='caregiverskills',
            name='communication_skills',
            field=models.JSONField(blank=True, default=list, help_text='چندانتخابی', verbose_name='مهارت\u200cهای ارتباطی'),
        ),
        migrations.AlterField(
            model_name='caregiverskills',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='caregiverskills',
            name='education_level',
            field=models.CharField(choices=[('under_diploma', 'زیر دیپلم'), ('diploma', 'دیپلم'), ('associate', 'کاردانی'), ('bachelor', 'کارشناسی'), ('master', 'کارشناسی ارشد'), ('phd', 'دکتری')], max_length=20, verbose_name='سطح تحصیلات'),
        ),
        migrations.AlterField(
            model_name='caregiverskills',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=150, verbose_name='رشته تحصیلی'),
        ),
        migrations.AlterField(
            model_name='caregiverskills',
            name='foreign_languages',
            field=models.JSONField(blank=True, default=list, help_text='چندانتخابی', verbose_name='زبان\u200cهای خارجی'),
        ),
        migrations.AlterField(
            model_name='caregiverskills',
            name='has_driving_license',
            field=models.BooleanField(blank=True, null=True, verbose_name='دارا بودن گواهینامه رانندگی'),
        ),
        migrations.AlterField(
            model_name='caregiverskills',
            name='has_personal_car',
            field=models.BooleanField(blank=True, null=True, verbose_name='دارا بودن ماشین شخصی'),
        ),
        migrations.AlterField(
            model_name='caregiverskills',
            name='household_skills',
            field=models.JSONField(blank=True, default=list, help_text='چندانتخابی', verbose_name='مهارت\u200cهای خانگی'),
        ),
        migrations.AlterField(
            model_name='caregiverskills',
            name='local_languages',
            field=models.JSONField(blank=True, default=list, help_text='چندانتخابی', verbose_name='زبان\u200cهای محلی'),
        ),
        migrations.AlterField(
            model_name='caregiverskills',
            name='mobility_assistance_ability',
            field=models.JSONField(blank=True, default=list, help_text='چندانتخابی', verbose_name='توانایی کمک به حرکت'),
        ),
        migrations.AlterField(
            model_name='caregiverskills',
            name='physical_ability',
            field=models.CharField(blank=True, choices=[('weak', 'ضعیف'), ('moderate', 'متوسط'), ('good', 'خوب'), ('very_good', 'بسیار خوب')], max_length=20, verbose_name='توانایی فیزیکی'),
        ),
        migrations.AlterField(
            model_name='caregiverskills',
            name='preferred_messaging_apps',
            field=models.JSONField(blank=True, default=list, help_text='چندانتخابی', verbose_name='اپلیکیشن\u200cهای پیام رسانی'),
        ),
        migrations.AlterField(
            model_name='caregiverskills',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='caregivers.caregiverprofile', verbose_name='پروفایل مراقب'),
        ),
        migrations.AlterField(
            model_name='caregiverskills',
            name='training_courses',
            field=models.JSONField(blank=True, default=list, help_text='چندانتخابی', verbose_name='دوره\u200cهای آموزشی'),
        ),
        migrations.AlterField(
            model_name='caregiverskills',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ و زمان بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='caregiverworkpreferences',
            name='accepted_age_ranges',
            field=models.JSONField(default=list, help_text='چندانتخابی — لیستی از AcceptedAgeRange', verbose_name='محدوده سنی پذیرفته'),
        ),
        migrations.AlterField(
            model_name='caregiverworkpreferences',
            name='accepted_gender',
            field=models.CharField(choices=[('female_only', 'فقط خانم'), ('male_only', 'فقط آقا'), ('no_preference', 'تفاوتی ندارد')], max_length=20, verbose_name='جنسیت پذیرفته'),
        ),
        migrations.AlterField(
            model_name='caregiverworkpreferences',
            name='accepted_physical_conditions',
            field=models.JSONField(default=list, help_text='چندانتخابی', verbose_name='شرایط فیزیکی پذیرفته'),
        ),
        migrations.AlterField(
            model_name='caregiverworkpreferences',
            name='available_days',
            field=models.JSONField(default=list, help_text='چندانتخابی — لیستی از Weekday', verbose_name='روزهای در دسترس'),
        ),
        migrations.AlterField(
            model_name='caregiverworkpreferences',
            name='available_shifts',
            field=models.JSONField(default=list, help_text='چندانتخابی — لیستی از Shift؛ نکته تودرتو در کلاس Shift', verbose_name='شیفت\u200cهای در دسترس'),
        ),
        migrations.AlterField(
            model_name='caregiverworkpreferences',
            name='collaboration_types',
            field=models.JSONField(default=list, help_text='چندانتخابی — لیستی از CollaborationType', verbose_name='نوع همکاری'),
        ),
        migrations.AlterField(
            model_name='caregiverworkpreferences',
            name='commute_methods',
            field=models.JSONField(blank=True, default=list, help_text='چندانتخابی — لیستی از CommuteMethod', verbose_name='روش\u200cهای مسافرت'),
        ),
        migrations.AlterField(
            model_name='caregiverworkpreferences',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='caregiverworkpreferences',
            name='family_presence_preference',
            field=models.CharField(choices=[('prefer_present', 'ترجیح می\u200cدهم عضوی از خانواده در منزل حضور داشته باشد'), ('prefer_absent', 'ترجیح می\u200cدهم خانواده در ساعات کاری خارج از منزل باشند'), ('no_preference', 'برایم اولویت ندارد')], max_length=20, verbose_name='ترجیح حضور خانواده'),
        ),
        migrations.AlterField(
            model_name='caregiverworkpreferences',
            name='holiday_work_ok',
            field=models.BooleanField(blank=True, null=True, verbose_name='پذیرش کار در روزهای تعطیل'),
        ),
        migrations.AlterField(
            model_name='caregiverworkpreferences',
            name='lifting_capacity',
            field=models.CharField(choices=[('up_to_30kg', 'تا ۳۰ کیلوگرم'), ('up_to_50kg', 'تا ۵۰ کیلوگرم'), ('over_50kg', 'بیش از ۵۰ کیلوگرم'), ('cannot_lift', 'امکان جابجایی فیزیکی ندارم')], max_length=20, verbose_name='ظرفیت جابجایی اجسام فیزیکی'),
        ),
        migrations.AlterField(
            model_name='caregiverworkpreferences',
            name='max_commute_time',
            field=models.CharField(blank=True, choices=[('up_to_60', 'تا ۶۰ دقیقه'), ('up_to_90', 'تا ۹۰ دقیقه'), ('over_90', 'بیش از ۹۰ دقیقه')], max_length=20, verbose_name='حداکثر زمان رفت\u200cوآمد'),
        ),
        migrations.AlterField(
            model_name='caregiverworkpreferences',
            name='offered_services',
            field=models.JSONField(default=list, help_text='چندانتخابی — لیستی از OfferedService', verbose_name='خدمات پیشنهادی'),
        ),
        migrations.AlterField(
            model_name='caregiverworkpreferences',
            name='overnight_stay_ok',
            field=models.BooleanField(blank=True, null=True, verbose_name='پذیرش اقامت شبانه روزی'),
        ),
        migrations.AlterField(
            model_name='caregiverworkpreferences',
            name='pets_ok',
            field=models.BooleanField(blank=True, null=True, verbose_name='پذیرش حیوان خانگی'),
        ),
        migrations.AlterField(
            model_name='caregiverworkpreferences',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_preferences', to='caregivers.caregiverprofile', verbose_name='پروفایل'),
        ),
        migrations.AlterField(
            model_name='caregiverworkpreferences',
            name='service_locations',
            field=models.JSONField(default=list, help_text='چندانتخابی — لیستی از ServiceLocation', verbose_name='محل\u200cهای خدماتی'),
        ),
        migrations.AlterField(
            model_name='caregiverworkpreferences',
            name='smoking_status',
            field=models.CharField(blank=True, choices=[('none', 'استعمال نمی\u200cکنم'), ('occasional', 'گهگاه استعمال می\u200cکنم'), ('regular', 'به\u200cصورت منظم استعمال می\u200cکنم')], max_length=20, verbose_name='وضعیت استعمال دخانیات'),
        ),
        migrations.AlterField(
            model_name='caregiverworkpreferences',
            name='terms_accepted',
            field=models.BooleanField(default=False, verbose_name='تأییدیه\u200cها'),
        ),
        migrations.AlterField(
            model_name='caregiverworkpreferences',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و زمان تأییدیه\u200cها'),
        ),
        migrations.AlterField(
            model_name='caregiverworkpreferences',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ و زمان بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='caregiverworkpreferences',
            name='work_status',
            field=models.CharField(choices=[('full_time', 'تمام\u200cوقت'), ('part_time', 'پاره\u200cوقت'), ('both', 'هر دو مورد')], max_length=20, verbose_name='وضعیت کار'),
        ),
    ]
