# Generated by Django 6.0.7 on 2026-08-05 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregivers', '0002_create_supervisor_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiverprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='ناظری که این مراقب را وارد سیستم کرده — خالی یعنی خود مراقب یا مسیر دیگری بوده.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_caregivers', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cشده توسط'),
        ),
    ]
