# Generated by Django 6.0.7 on 2026-08-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregivers', '0003_caregiverprofile_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityprofile',
            name='military_status',
            field=models.CharField(blank=True, choices=[('not_served', 'مشمول (هنوز به خدمت نرفته)'), ('in_service', 'در حال خدمت'), ('completed', 'پایان خدمت'), ('permanent_exemption', 'معافیت دائم'), ('temporary_exemption', 'معافیت موقت')], help_text='فقط برای جنسیت مرد', max_length=30, null=True, verbose_name='وضعیت نظام وظیفه'),
        ),
    ]
