# Generated by Django 6.0.7 on 2026-08-14 10:30

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregivers', '0004_alter_identityprofile_military_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverCompatibilityQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('religious_belief_accommodation', models.CharField(choices=[('a', 'گزینه الف'), ('b', 'گزینه ب'), ('c', 'گزینه ج'), ('d', 'گزینه د')], max_length=1, verbose_name='پذیرش باور مذهبی متفاوت سالمند')),
                ('physical_contact_sensitivity_adaptation', models.CharField(choices=[('a', 'گزینه الف'), ('b', 'گزینه ب'), ('c', 'گزینه ج'), ('d', 'گزینه د')], max_length=1, verbose_name='تطبیق با حساسیت فرهنگی نسبت به تماس بدنی')),
                ('prayer_time_scheduling_flexibility', models.CharField(choices=[('a', 'گزینه الف'), ('b', 'گزینه ب'), ('c', 'گزینه ج'), ('d', 'گزینه د')], max_length=1, verbose_name='هماهنگی برنامه مراقبتی با مناسک مذهبی')),
                ('traditional_belief_acceptance', models.CharField(choices=[('a', 'گزینه الف'), ('b', 'گزینه ب'), ('c', 'گزینه ج'), ('d', 'گزینه د')], max_length=1, verbose_name='پذیرش باور سنتی غیرعلمی سالمند')),
                ('family_event_participation', models.CharField(choices=[('a', 'گزینه الف'), ('b', 'گزینه ب'), ('c', 'گزینه ج'), ('d', 'گزینه د')], max_length=1, verbose_name='حضور در مناسبت\u200cهای خانوادگی')),
                ('false_accusation_reaction', models.CharField(choices=[('a', 'گزینه الف'), ('b', 'گزینه ب'), ('c', 'گزینه ج'), ('d', 'گزینه د')], max_length=1, verbose_name='واکنش به اتهام ناشی از فراموشی سالمند')),
                ('confidentiality_commitment', models.CharField(choices=[('a', 'گزینه الف'), ('b', 'گزینه ب'), ('c', 'گزینه ج'), ('d', 'گزینه د')], max_length=1, verbose_name='تعهد به محرمانگی اطلاعات')),
                ('gender_based_task_flexibility', models.CharField(choices=[('a', 'گزینه الف'), ('b', 'گزینه ب'), ('c', 'گزینه ج'), ('d', 'گزینه د')], max_length=1, verbose_name='انعطاف در محدودیت وظایف بر اساس جنسیت')),
                ('home_environment_adaptability', models.CharField(choices=[('a', 'گزینه الف'), ('b', 'گزینه ب'), ('c', 'گزینه ج'), ('d', 'گزینه د')], max_length=1, verbose_name='سازگاری با شرایط فیزیکی خانه سالمند')),
                ('schedule_flexibility_for_family_events', models.CharField(choices=[('a', 'گزینه الف'), ('b', 'گزینه ب'), ('c', 'گزینه ج'), ('d', 'گزینه د')], max_length=1, verbose_name='انعطاف برنامه در تداخل با رویداد خانوادگی')),
                ('traditional_food_treatment_openness', models.CharField(choices=[('a', 'گزینه الف'), ('b', 'گزینه ب'), ('c', 'گزینه ج'), ('d', 'گزینه د')], max_length=1, verbose_name='باز بودن به غذا و درمان سنتی سالمند')),
                ('personal_conversation_patience', models.CharField(choices=[('a', 'گزینه الف'), ('b', 'گزینه ب'), ('c', 'گزینه ج'), ('d', 'گزینه د')], max_length=1, verbose_name='صبر برای گفت\u200cوگوی شخصی سالمند')),
                ('home_organization_adaptability', models.CharField(choices=[('a', 'گزینه الف'), ('b', 'گزینه ب'), ('c', 'گزینه ج'), ('d', 'گزینه د')], max_length=1, verbose_name='سازگاری با نظم و چیدمان خانه سالمند')),
                ('cultural_expression_tolerance', models.CharField(choices=[('a', 'گزینه الف'), ('b', 'گزینه ب'), ('c', 'گزینه ج'), ('d', 'گزینه د')], max_length=1, verbose_name='تحمل بیان و شوخی\u200cهای فرهنگی متفاوت')),
                ('unfamiliar_custom_acceptance', models.CharField(choices=[('a', 'گزینه الف'), ('b', 'گزینه ب'), ('c', 'گزینه ج'), ('d', 'گزینه د')], max_length=1, verbose_name='پذیرش رسوم ناآشنای خانواده سالمند')),
                ('dialect_communication_effort', models.CharField(choices=[('a', 'گزینه الف'), ('b', 'گزینه ب'), ('c', 'گزینه ج'), ('d', 'گزینه د')], max_length=1, verbose_name='تلاش برای ارتباط با وجود تفاوت لهجه')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان تکمیل')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('caregiver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_questionnaire', to='caregivers.caregiverprofile', verbose_name='مراقب')),
            ],
            options={
                'verbose_name': 'پرسشنامه سازگاری مراقب',
                'verbose_name_plural': 'پرسشنامه\u200cهای سازگاری مراقبان',
            },
        ),
    ]
