# Generated by Django 6.0.7 on 2026-08-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregivers', '0005_caregivercompatibilityquestionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiverprofile',
            name='blacklist_reason',
            field=models.TextField(
                blank=True,
                help_text='فقط وقتی status برابر suspended باشد معنا دارد — یک مراقب تأییدشده که بعداً مسدود شده، نه یک درخواست رد‌شده.',
                verbose_name='دلیل مسدودسازی',
            ),
        ),
    ]
