# Generated by Django 6.0.7 on 2026-08-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregivers', '0006_caregiverprofile_blacklist_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiverprofile',
            name='status',
            field=models.CharField(
                choices=[
                    ('draft', 'پیش‌نویس'), ('pending', 'در انتظار بررسی'),
                    ('approved', 'تأیید شده'), ('rejected', 'رد شده'), ('suspended', 'تعلیق شده'),
                ],
                db_index=True, default='draft', max_length=20, verbose_name='وضعیت ثبت‌ نام',
            ),
        ),
    ]
