# Generated by Django 6.0.7 on 2026-09-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caregivers", "0009_candidate_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="caregiverworkpreferences",
            name="additional_notes",
            field=models.TextField(
                blank=True, max_length=500, verbose_name="توضیحات تکمیلی"
            ),
        ),
        migrations.AddField(
            model_name="caregiverworkpreferences",
            name="has_night_time_limit",
            field=models.BooleanField(
                blank=True,
                default=None,
                null=True,
                verbose_name="محدودیت زمانی برای شب دارد",
            ),
        ),
        migrations.AddField(
            model_name="caregiverworkpreferences",
            name="night_stay_until",
            field=models.CharField(
                blank=True,
                choices=[
                    ("up_to_10pm", "تا ۱۰ شب"),
                    ("up_to_midnight", "تا ۱۲ شب"),
                    ("up_to_2am", "تا ۲ بامداد"),
                    ("until_morning", "تا صبح"),
                ],
                max_length=20,
                verbose_name="حداکثر زمان ماندن در شب",
            ),
        ),
    ]
