# Generated by Django 6.0.7 on 2026-09-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caregivers", "0010_caregiverworkpreferences_additional_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="caregiverprofile",
            name="serves_all_areas",
            field=models.BooleanField(
                default=False,
                help_text="اگر فعال باشد، این مراقب محدود به مناطق خدماتی ثبت\u200cشده نیست و برای تمام مناطق در نظر گرفته می\u200cشود.",
                verbose_name="پوشش تمام مناطق",
            ),
        ),
    ]
