# Generated by Django 6.0.7 on 2026-09-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caregivers", "0011_caregiverprofile_serves_all_areas"),
    ]

    operations = [
        migrations.AddField(
            model_name="caregiverprofile",
            name="agency_pipeline_status",
            field=models.CharField(
                choices=[
                    ("registered", "ثبت در سایت"),
                    ("documents_in_progress", "تکمیل مدارک"),
                    ("being_dispatched", "در حال اعزام"),
                    ("on_assignment", "در حال مأموریت"),
                    ("first_week", "هفته اول"),
                    ("confirmed", "تأیید شده"),
                    ("expired", "منقضی\u200cها"),
                ],
                db_index=True,
                default="registered",
                max_length=30,
                verbose_name="مرحله کاریز خدمت (آژانس)",
            ),
        ),
        migrations.AddField(
            model_name="caregiverprofile",
            name="doc_id_card_received",
            field=models.BooleanField(
                default=False, verbose_name="دریافت مدرک شناسایی"
            ),
        ),
        migrations.AddField(
            model_name="caregiverprofile",
            name="doc_identity_verified",
            field=models.BooleanField(default=False, verbose_name="تأیید مدارک هویتی"),
        ),
        migrations.AddField(
            model_name="caregiverprofile",
            name="doc_mental_health_test",
            field=models.BooleanField(default=False, verbose_name="آزمون سلامت روان"),
        ),
        migrations.AddField(
            model_name="caregiverprofile",
            name="doc_no_addiction_test",
            field=models.BooleanField(default=False, verbose_name="آزمایش عدم اعتیاد"),
        ),
        migrations.AddField(
            model_name="caregiverprofile",
            name="doc_no_criminal_record",
            field=models.BooleanField(default=False, verbose_name="عدم سوءپیشینه"),
        ),
        migrations.AddField(
            model_name="caregiverprofile",
            name="doc_personal_photo",
            field=models.BooleanField(default=False, verbose_name="عکس پرسنلی"),
        ),
        migrations.AddField(
            model_name="caregiverprofile",
            name="doc_promissory_note",
            field=models.BooleanField(default=False, verbose_name="دریافت سفته/ضمانت"),
        ),
        migrations.AddField(
            model_name="caregiverprofile",
            name="is_urgent",
            field=models.BooleanField(
                default=False,
                help_text="برچسب فوری روی کارت این مراقب در کاریز آژانس نمایش داده می\u200cشود.",
                verbose_name="فوری",
            ),
        ),
    ]
