# Generated by Django 6.0.7 on 2026-09-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caregivers", "0012_caregiverprofile_agency_pipeline_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="caregiverprofile",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="برچسب\u200cهای آزاد آژانس روی این مراقب — مثلاً دسته خدمت (پرستار، بهیار، سالمندیار) یا هر برچسب دیگری، برای دسته\u200cبندی و فیلتر آینده کاریز.",
                verbose_name="برچسب\u200cها",
            ),
        ),
    ]
