# Generated by Django 6.0.7 on 2026-09-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caregivers", "0013_caregiverprofile_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caregiverprofile",
            name="agency_pipeline_status",
            field=models.CharField(
                choices=[
                    ("availability", "در دسترس بودن"),
                    ("after_match", "پس از تطبیق"),
                    ("caregiver_coordination", "هماهنگی با خدمت\u200cدهنده"),
                    ("patient_coordination", "هماهنگی با خدمت\u200cگیرنده"),
                    ("dispatch", "اعزام نیرو"),
                    ("final_confirmation", "تایید نهایی"),
                    ("caregiver_support", "پشتیبانی خدمت\u200cدهنده"),
                    ("patient_support", "پشتیبانی خدمت\u200cگیرنده"),
                    ("mutual_survey", "نظرسنجی طرفین از تطبیق"),
                    ("contract_ending_soon", "در شرف اتمام قرارداد"),
                    ("contract_renewal", "تمدید قرارداد"),
                    ("contract_completed", "اتمام قرارداد"),
                ],
                db_index=True,
                default="availability",
                max_length=30,
                verbose_name="مرحله کاریز خدمت (آژانس)",
            ),
        ),
    ]
