# Generated by Django 6.0.7 on 2026-09-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caregivers", "0014_alter_caregiverprofile_agency_pipeline_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="caregiverprofile",
            name="process_milestones",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="زیرمجموعه\u200cای از CaregiverProcessMilestone که هم\u200cاکنون روی این مراقب صدق می\u200cکند — جدا از agency_pipeline_status بالا.",
                verbose_name="نقاط عطف فرآیند تطبیق",
            ),
        ),
        migrations.AlterField(
            model_name="caregiverprofile",
            name="agency_pipeline_status",
            field=models.CharField(
                choices=[
                    ("registered", "ثبت در سایت"),
                    ("documents_in_progress", "تکمیل مدارک"),
                    ("being_dispatched", "در حال اعزام"),
                    ("on_assignment", "در حال مأموریت"),
                    ("first_week", "هفته اول"),
                    ("confirmed", "تأیید شده"),
                    ("expired", "منقضی\u200cها"),
                ],
                db_index=True,
                default="registered",
                max_length=30,
                verbose_name="مرحله کاریز خدمت (آژانس)",
            ),
        ),
    ]
