# Generated by Django 5.2.17 on 2026-09-27 11:25

import apps.caregivers.models
import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caregivers", "0015_caregiverprofile_process_milestones_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaregiverDocumentUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("no_criminal_record", "عدم سوءپیشینه"),
                            ("no_addiction_test", "آزمایش عدم اعتیاد"),
                            ("identity_verified", "تأیید مدارک هویتی"),
                            ("personal_photo", "عکس پرسنلی"),
                            ("mental_health_test", "آزمون سلامت روان"),
                            ("promissory_note", "دریافت سفته/ضمانت"),
                            ("id_card_received", "دریافت مدرک شناسایی"),
                        ],
                        max_length=30,
                        verbose_name="نوع مدرک",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.caregivers.models.caregiver_document_upload_path,
                        verbose_name="فایل",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار بررسی"),
                            ("approved", "تأیید شده"),
                            ("rejected", "رد شده"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت بررسی",
                    ),
                ),
                (
                    "uploaded_at",
                    django_jalali.db.models.jDateTimeField(
                        auto_now=True, verbose_name="زمان بارگذاری"
                    ),
                ),
                (
                    "reviewed_at",
                    django_jalali.db.models.jDateTimeField(
                        blank=True, null=True, verbose_name="زمان بررسی"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="دلیل رد شدن"),
                ),
                (
                    "caregiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_uploads",
                        to="caregivers.caregiverprofile",
                        verbose_name="مراقب",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="caregiver_documents_reviewed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="بررسی\u200cکننده",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="caregiver_documents_uploaded",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="بارگذاری\u200cکننده",
                    ),
                ),
            ],
            options={
                "verbose_name": "مدرک بارگذاری\u200cشده مراقب",
                "verbose_name_plural": "مدارک بارگذاری\u200cشده مراقبان",
                "unique_together": {("caregiver", "document_type")},
            },
        ),
    ]
