# Generated by Django 5.2.17 on 2026-09-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caregivers", "0016_caregiverdocumentupload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caregiverprofile",
            name="agency_pipeline_status",
            field=models.CharField(
                db_index=True,
                default="registered",
                max_length=30,
                verbose_name="مرحله کاریز خدمت (آژانس)",
            ),
        ),
    ]
