# Generated by Django 5.2.17 on 2026-09-29 10:42

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("caregivers", "0017_alter_caregiverprofile_agency_pipeline_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="caregiverprofile",
            name="contract_end_date",
            field=django_jalali.db.models.jDateField(
                blank=True,
                help_text="از زمانی که این مراقب وارد مرحله «در حال مأموریت» می\u200cشود ثبت می\u200cشود — برای پیگیری نزدیک\u200cشدن به پایان قرارداد.",
                null=True,
                verbose_name="تاریخ پایان قرارداد فعلی",
            ),
        ),
    ]
