# Generated by Django 5.2.17 on 2026-09-30 06:13

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("caregivers", "0018_caregiverprofile_contract_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="caregiverprofile",
            name="contract_start_date",
            field=django_jalali.db.models.jDateField(
                blank=True,
                help_text="تاریخ شروع همان قرارداد فعلی — در همان مرحله «در حال مأموریت» ثبت می\u200cشود، کنار تاریخ پایان.",
                null=True,
                verbose_name="تاریخ شروع قرارداد فعلی",
            ),
        ),
    ]
