# Generated by Django 5.2.17 on 2026-09-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caregivers", "0019_caregiverprofile_contract_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="caregiverworkpreferences",
            name="daily_work_hours",
            field=models.CharField(
                blank=True,
                help_text="فقط برای «مراقبت روزانه» — مثلاً «از ساعت ۸ تا ۱۶».",
                max_length=100,
                verbose_name="ساعات کاری مراقبت روزانه",
            ),
        ),
        migrations.AddField(
            model_name="caregiverworkpreferences",
            name="requested_salary",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="حقوق درخواستی"
            ),
        ),
        migrations.AddField(
            model_name="identityprofile",
            name="national_id",
            field=models.CharField(blank=True, max_length=10, verbose_name="شماره ملی"),
        ),
    ]
