# Generated by Django 5.2.17 on 2026-09-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caregivers", "0020_national_id_daily_hours_salary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="caregivercompatibilityquestionnaire",
            name="confidentiality_commitment",
        ),
        migrations.RemoveField(
            model_name="caregivercompatibilityquestionnaire",
            name="cultural_expression_tolerance",
        ),
        migrations.RemoveField(
            model_name="caregivercompatibilityquestionnaire",
            name="dialect_communication_effort",
        ),
        migrations.RemoveField(
            model_name="caregivercompatibilityquestionnaire",
            name="false_accusation_reaction",
        ),
        migrations.RemoveField(
            model_name="caregivercompatibilityquestionnaire",
            name="family_event_participation",
        ),
        migrations.RemoveField(
            model_name="caregivercompatibilityquestionnaire",
            name="gender_based_task_flexibility",
        ),
        migrations.RemoveField(
            model_name="caregivercompatibilityquestionnaire",
            name="home_environment_adaptability",
        ),
        migrations.RemoveField(
            model_name="caregivercompatibilityquestionnaire",
            name="home_organization_adaptability",
        ),
        migrations.RemoveField(
            model_name="caregivercompatibilityquestionnaire",
            name="personal_conversation_patience",
        ),
        migrations.RemoveField(
            model_name="caregivercompatibilityquestionnaire",
            name="physical_contact_sensitivity_adaptation",
        ),
        migrations.RemoveField(
            model_name="caregivercompatibilityquestionnaire",
            name="prayer_time_scheduling_flexibility",
        ),
        migrations.RemoveField(
            model_name="caregivercompatibilityquestionnaire",
            name="religious_belief_accommodation",
        ),
        migrations.RemoveField(
            model_name="caregivercompatibilityquestionnaire",
            name="schedule_flexibility_for_family_events",
        ),
        migrations.RemoveField(
            model_name="caregivercompatibilityquestionnaire",
            name="traditional_belief_acceptance",
        ),
        migrations.RemoveField(
            model_name="caregivercompatibilityquestionnaire",
            name="traditional_food_treatment_openness",
        ),
        migrations.RemoveField(
            model_name="caregivercompatibilityquestionnaire",
            name="unfamiliar_custom_acceptance",
        ),
        migrations.AddField(
            model_name="caregivercompatibilityquestionnaire",
            name="clinical_compatibility_level",
            field=models.CharField(
                choices=[("0", "هیچ\u200cوجه"), ("50", "تا حدی"), ("100", "کاملاً")],
                default="50",
                max_length=3,
                verbose_name="سازگاری بالینی",
            ),
        ),
        migrations.AddField(
            model_name="caregivercompatibilityquestionnaire",
            name="family_compatibility_level",
            field=models.CharField(
                choices=[("0", "هیچ\u200cوجه"), ("50", "تا حدی"), ("100", "کاملاً")],
                default="50",
                max_length=3,
                verbose_name="سازگاری با خانواده سالمند",
            ),
        ),
        migrations.AddField(
            model_name="caregivercompatibilityquestionnaire",
            name="patience_level",
            field=models.CharField(
                choices=[("0", "هیچ\u200cوجه"), ("50", "تا حدی"), ("100", "کاملاً")],
                default="50",
                max_length=3,
                verbose_name="میزان صبوری",
            ),
        ),
        migrations.AddField(
            model_name="caregivercompatibilityquestionnaire",
            name="religiosity_level",
            field=models.CharField(
                choices=[("0", "هیچ\u200cوجه"), ("50", "تا حدی"), ("100", "کاملاً")],
                default="50",
                max_length=3,
                verbose_name="میزان مذهبی بودن",
            ),
        ),
    ]
