# Generated by Django 5.2.17 on 2026-10-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caregivers", "0021_replace_compatibility_questionnaire"),
    ]

    operations = [
        migrations.AddField(
            model_name="caregiverworkpreferences",
            name="cleaning_willingness",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "نظافت را انجام نمی\u200cدهد"),
                    ("light", "نظافت سبک انجام می\u200cدهد"),
                    ("heavy", "نظافت سنگین انجام می\u200cدهد"),
                ],
                max_length=10,
                verbose_name="میزان انجام نظافت",
            ),
        ),
        migrations.AddField(
            model_name="caregiverworkpreferences",
            name="day_off_request",
            field=models.CharField(
                blank=True,
                help_text="توضیح آزاد — مثلاً «جمعه\u200cها» یا «هماهنگ می\u200cشود».",
                max_length=200,
                verbose_name="روز درخواستی برای تعطیلی",
            ),
        ),
        migrations.AddField(
            model_name="identityprofile",
            name="psychiatric_medication_detail",
            field=models.TextField(
                blank=True,
                help_text="فقط وقتی «مشکلات روحی و روانی» در نوع بیماری انتخاب شده باشد.",
                max_length=500,
                verbose_name="داروهای مصرفی برای مشکلات روحی/روانی",
            ),
        ),
    ]
