# Generated by Django 5.2.17 on 2026-10-02 06:41

from django.db import migrations, models


def backfill_salmandyar(apps, schema_editor):
    """Every caregiver that existed before this field did was
    registered through the (until now, only) سالمندیار wizard — tag
    them all accordingly so nothing already in the system silently
    disappears from every pool once pool filtering ships."""
    CaregiverProfile = apps.get_model("caregivers", "CaregiverProfile")
    CaregiverProfile.objects.filter(service_types=[]).update(service_types=["salmandyar"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("caregivers", "0022_caregiverworkpreferences_cleaning_willingness_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="caregiverprofile",
            name="service_subtypes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='دیکشنری {نوع خدمت: [زیرشاخه\u200cهای انتخابی]} — مثلاً {"nezafatchi": ["cooking", "inside_home"]}.',
                verbose_name="زیرشاخه نوع خدمت",
            ),
        ),
        migrations.AddField(
            model_name="caregiverprofile",
            name="service_types",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="یک یا چند مورد از: سالمندیار، کودک\u200cیار، نظافت\u200cچی، مادریار، پرستار، بهیار.",
                verbose_name="نوع خدمت",
            ),
        ),
        migrations.RunPython(backfill_salmandyar, noop_reverse),
    ]
