# Generated by Django 5.2.17 on 2026-10-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "caregivers",
            "0024_caregivercompatibilityquestionnaire_service_specific_answers_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="caregiverskills",
            name="arabic_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "هیچ"),
                    ("basic", "مقدماتی"),
                    ("intermediate", "متوسط"),
                    ("fluent", "پیشرفته / روان"),
                ],
                max_length=20,
                verbose_name="میزان تسلط به زبان عربی",
            ),
        ),
        migrations.AddField(
            model_name="caregiverskills",
            name="english_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "هیچ"),
                    ("basic", "مقدماتی"),
                    ("intermediate", "متوسط"),
                    ("fluent", "پیشرفته / روان"),
                ],
                max_length=20,
                verbose_name="میزان تسلط به زبان انگلیسی",
            ),
        ),
        migrations.AddField(
            model_name="caregiverworkpreferences",
            name="ok_with_father_absent_at_home",
            field=models.BooleanField(
                blank=True,
                default=None,
                null=True,
                verbose_name="تمایل به کار در خانواده\u200cای که پدر در ساعات کاری در منزل نیست",
            ),
        ),
        migrations.AddField(
            model_name="caregiverworkpreferences",
            name="ok_with_grandparent_or_relative_at_home",
            field=models.BooleanField(
                blank=True,
                default=None,
                null=True,
                verbose_name="تمایل به کار در خانواده\u200cای که پدربزرگ/مادربزرگ یا یکی از اقوام هم در منزل حضور دارد",
            ),
        ),
        migrations.AddField(
            model_name="caregiverworkpreferences",
            name="ok_with_home_camera",
            field=models.BooleanField(
                blank=True,
                default=None,
                null=True,
                verbose_name="تمایل به کار در منزلی که دوربین مداربسته دارد",
            ),
        ),
        migrations.AddField(
            model_name="caregiverworkpreferences",
            name="ok_with_single_father",
            field=models.BooleanField(
                blank=True,
                default=None,
                null=True,
                verbose_name="تمایل به کار نزد پدر مجرد",
            ),
        ),
        migrations.AddField(
            model_name="caregiverworkpreferences",
            name="ok_with_single_mother",
            field=models.BooleanField(
                blank=True,
                default=None,
                null=True,
                verbose_name="تمایل به کار نزد مادر تنها (بدون همسر)",
            ),
        ),
        migrations.AddField(
            model_name="caregiverworkpreferences",
            name="pets_cat_ok",
            field=models.BooleanField(
                blank=True,
                default=None,
                null=True,
                verbose_name="سازگاری با حضور گربه در منزل",
            ),
        ),
        migrations.AddField(
            model_name="caregiverworkpreferences",
            name="pets_dog_ok",
            field=models.BooleanField(
                blank=True,
                default=None,
                null=True,
                verbose_name="سازگاری با حضور سگ در منزل",
            ),
        ),
        migrations.AddField(
            model_name="caregiverworkpreferences",
            name="pets_other_notes",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="سایر حیوانات خانگی"
            ),
        ),
        migrations.AddField(
            model_name="caregiverworkpreferences",
            name="travel_domestic_ok",
            field=models.BooleanField(
                blank=True,
                default=None,
                null=True,
                verbose_name="آمادگی سفر همراه خانواده در داخل ایران",
            ),
        ),
        migrations.AddField(
            model_name="caregiverworkpreferences",
            name="travel_international_ok",
            field=models.BooleanField(
                blank=True,
                default=None,
                null=True,
                verbose_name="آمادگی سفر همراه خانواده به خارج از کشور",
            ),
        ),
        migrations.AddField(
            model_name="identityprofile",
            name="currently_caring_for_own_child",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="برای سنجش هم\u200cزمانی مراقبت از فرزند خودش با کار — فقط وقتی has_children=True معنا دارد.",
                null=True,
                verbose_name="آیا در حال حاضر از فرزند خود مراقبت می\u200cکند؟",
            ),
        ),
        migrations.AddField(
            model_name="identityprofile",
            name="has_children",
            field=models.BooleanField(
                blank=True,
                default=None,
                null=True,
                verbose_name="آیا خودتان فرزند دارید؟",
            ),
        ),
    ]
