# Generated by Django 5.2.17 on 2026-10-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "caregivers",
            "0024_caregivercompatibilityquestionnaire_service_specific_answers_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="caregiverskills",
            name="arabic_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "هیچ"),
                    ("basic", "مقدماتی"),
                    ("intermediate", "متوسط"),
                    ("fluent", "پیشرفته / روان"),
                ],
                max_length=20,
                verbose_name="میزان تسلط به زبان عربی",
            ),
        ),
        migrations.AddField(
            model_name="caregiverskills",
            name="english_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "هیچ"),
                    ("basic", "مقدماتی"),
                    ("intermediate", "متوسط"),
                    ("fluent", "پیشرفته / روان"),
                ],
                max_length=20,
                verbose_name="میزان تسلط به زبان انگلیسی",
            ),
        ),
        migrations.AddField(
            model_name="caregiverskills",
            name="other_languages_detail",
            field=models.CharField(
                blank=True,
                help_text="متن آزاد — مثلاً «ترکی استانبولی - متوسط».",
                max_length=300,
                verbose_name="سایر زبان\u200cها و سطح آن\u200cها",
            ),
        ),
        migrations.AddField(
            model_name="caregiverworkpreferences",
            name="pay_basis",
            field=models.CharField(
                blank=True,
                choices=[
                    ("hourly", "ساعتی"),
                    ("shift", "شیفتی"),
                    ("daily", "روزانه"),
                    ("monthly", "ماهانه"),
                ],
                help_text="فیلد عمومی — قبلاً سوال مجزا در کودک\u200cیار و مادریار بود، حالا یکی، کنار حقوق درخواستی.",
                max_length=20,
                verbose_name="مبنای دریافت حقوق",
            ),
        ),
        migrations.AddField(
            model_name="caregiverworkpreferences",
            name="pets_other_notes",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="سایر حیوانات خانگی"
            ),
        ),
        migrations.AddField(
            model_name="caregiverworkpreferences",
            name="problem_with_cat",
            field=models.BooleanField(
                blank=True,
                default=None,
                null=True,
                verbose_name="مشکل با حضور گربه در منزل",
            ),
        ),
        migrations.AddField(
            model_name="caregiverworkpreferences",
            name="problem_with_dog",
            field=models.BooleanField(
                blank=True,
                default=None,
                null=True,
                verbose_name="مشکل با حضور سگ در منزل",
            ),
        ),
        migrations.AddField(
            model_name="caregiverworkpreferences",
            name="problem_with_domestic_travel",
            field=models.BooleanField(
                blank=True,
                default=None,
                null=True,
                verbose_name="مشکل با سفر همراه خانواده در داخل ایران",
            ),
        ),
        migrations.AddField(
            model_name="caregiverworkpreferences",
            name="problem_with_father_present_at_home",
            field=models.BooleanField(
                blank=True,
                default=None,
                null=True,
                verbose_name="مشکل با کار در خانه\u200cای که پدر در ساعات کاری در منزل است",
            ),
        ),
        migrations.AddField(
            model_name="caregiverworkpreferences",
            name="problem_with_grandparent_or_relative_at_home",
            field=models.BooleanField(
                blank=True,
                default=None,
                null=True,
                verbose_name="مشکل با کار در خانه\u200cای که پدربزرگ/مادربزرگ یا یکی از اقوام هم حضور دارد",
            ),
        ),
        migrations.AddField(
            model_name="caregiverworkpreferences",
            name="problem_with_home_camera",
            field=models.BooleanField(
                blank=True,
                default=None,
                null=True,
                verbose_name="مشکل با کار در منزلی که دوربین مداربسته دارد",
            ),
        ),
        migrations.AddField(
            model_name="caregiverworkpreferences",
            name="problem_with_international_travel",
            field=models.BooleanField(
                blank=True,
                default=None,
                null=True,
                verbose_name="مشکل با سفر همراه خانواده به خارج از کشور",
            ),
        ),
        migrations.AddField(
            model_name="caregiverworkpreferences",
            name="problem_with_single_father",
            field=models.BooleanField(
                blank=True,
                default=None,
                null=True,
                verbose_name="مشکل با کار نزد پدر مجرد",
            ),
        ),
        migrations.AddField(
            model_name="caregiverworkpreferences",
            name="problem_with_single_mother",
            field=models.BooleanField(
                blank=True,
                default=None,
                null=True,
                verbose_name="مشکل با کار نزد مادر تنها (بدون همسر)",
            ),
        ),
        migrations.AddField(
            model_name="caregiverworkpreferences",
            name="problem_without_private_room",
            field=models.BooleanField(
                blank=True,
                default=None,
                null=True,
                verbose_name="مشکل با نبود اتاق شخصی در صورت ماندن شب",
            ),
        ),
        migrations.AddField(
            model_name="identityprofile",
            name="chronic_disease_detail",
            field=models.CharField(
                blank=True,
                help_text="متن آزاد — نام دقیق بیماری، کنار لیست انتخابی chronic_disease_types.",
                max_length=300,
                verbose_name="توضیح نوع بیماری",
            ),
        ),
        migrations.AddField(
            model_name="identityprofile",
            name="currently_caring_for_own_child",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="برای سنجش هم\u200cزمانی مراقبت از فرزند خودش با کار — فقط وقتی has_children=True معنا دارد.",
                null=True,
                verbose_name="آیا در حال حاضر از فرزند خود مراقبت می\u200cکند؟",
            ),
        ),
        migrations.AddField(
            model_name="identityprofile",
            name="has_children",
            field=models.BooleanField(
                blank=True,
                default=None,
                null=True,
                verbose_name="آیا خودتان فرزند دارید؟",
            ),
        ),
        migrations.AddField(
            model_name="identityprofile",
            name="medication_detail",
            field=models.CharField(
                blank=True,
                help_text="متن آزاد — نام دقیق دارو، کنار لیست انتخابی medication_types.",
                max_length=300,
                verbose_name="توضیح نوع دارو",
            ),
        ),
    ]
