# Generated by Django 5.2.17 on 2026-10-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caregivers", "0025_caregiverskills_arabic_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="caregiverskills",
            name="local_language_fluency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("understand_only", "فقط متوجه می\u200cشود"),
                    ("can_converse", "می\u200cتواند مکالمه کند"),
                ],
                max_length=20,
                verbose_name="سطح تسلط به زبان(های) محلی",
            ),
        ),
    ]
