# Generated by Django 5.2.17 on 2026-10-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caregivers", "0026_caregiverskills_local_language_fluency"),
    ]

    operations = [
        migrations.AddField(
            model_name="caregiverprofile",
            name="doc_residency_documents",
            field=models.BooleanField(default=False, verbose_name="مدارک اقامت اتباع"),
        ),
        migrations.AddField(
            model_name="identityprofile",
            name="is_non_iranian_national",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="تابعیت غیرایرانی (اتباع) دارد",
            ),
        ),
        migrations.AddField(
            model_name="identityprofile",
            name="nationality_country",
            field=models.CharField(
                blank=True,
                help_text="فقط در صورت تابعیت غیرایرانی.",
                max_length=100,
                verbose_name="اهل کدام کشور است",
            ),
        ),
        migrations.AlterField(
            model_name="caregiverdocumentupload",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("no_criminal_record", "عدم سوءپیشینه"),
                    ("no_addiction_test", "آزمایش عدم اعتیاد"),
                    ("identity_verified", "تأیید مدارک هویتی"),
                    ("personal_photo", "عکس پرسنلی"),
                    ("mental_health_test", "آزمون سلامت روان"),
                    ("residency_documents", "مدارک اقامت اتباع (پاسپورت/اقامت)"),
                    ("promissory_note", "دریافت سفته/ضمانت"),
                    ("id_card_received", "دریافت مدرک شناسایی"),
                ],
                max_length=30,
                verbose_name="نوع مدرک",
            ),
        ),
    ]
