# Generated by Django 5.2.17 on 2026-10-04 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caregivers", "0027_caregiverprofile_doc_residency_documents_and_more"),
        ("locations", "0009_alter_province_ordering_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="identityprofile",
            name="birth_certificate_issue_city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="locations.city",
                verbose_name="شهر محل صدور شناسنامه",
            ),
        ),
        migrations.AddField(
            model_name="identityprofile",
            name="birth_certificate_issue_province",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="locations.province",
                verbose_name="استان محل صدور شناسنامه",
            ),
        ),
        migrations.AddField(
            model_name="identityprofile",
            name="extra_phone_numbers",
            field=models.JSONField(
                blank=True, default=list, verbose_name="سایر شماره\u200cهای تماس"
            ),
        ),
        migrations.AddField(
            model_name="identityprofile",
            name="nursing_license_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="شماره پروانه نظام پرستاری"
            ),
        ),
        migrations.AlterField(
            model_name="identityprofile",
            name="birth_certificate_issue_place",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="محل صدور شناسنامه (قدیمی)"
            ),
        ),
    ]
