# Generated by Django 5.2.17 on 2026-10-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caregivers", "0028_identityprofile_birth_certificate_issue_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caregivercompatibilityquestionnaire",
            name="service_specific_answers",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="همان ساختار service_specific_answers در CaregiverWorkPreferences، اما برای چند سوال سازگاری اضافه که فقط برای یک نوع خدمت خاص معنا دارند (مثلاً «میزان صبر با کودکان» فقط برای مادریار) — هر مقدار همان مقیاس ۰/۵۰/۱۰۰ (ScoreAnswer) بالا را دنبال می\u200cکند. ۴ سوال عمومی بالا برای همه نوع\u200cهای خدمت ثابت می\u200cماند.",
                verbose_name="پاسخ\u200cهای سازگاری مخصوص نوع خدمت",
            ),
        ),
        migrations.AlterField(
            model_name="caregiverexperience",
            name="service_specific_answers",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="همان ساختار service_specific_answers در CaregiverWorkPreferences، اما برای سوالات فرم ۳ (سوابق و مهارت\u200cها) مخصوص هر نوع خدمت — تجربه و مهارت مخصوص امور منزل/مادریار/پرستار/بهیار همگی همین\u200cجا نگه داشته می\u200cشوند تا دو جدول اضافه برای مهارت\u200cهای تخصصی لازم نباشد.",
                verbose_name="پاسخ\u200cهای فرم ۳ مخصوص نوع خدمت",
            ),
        ),
        migrations.AlterField(
            model_name="caregiverprofile",
            name="service_types",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="یک یا چند مورد از: سالمندیار، امور منزل، مادریار (شامل کودک)، پرستار، بهیار.",
                verbose_name="نوع خدمت",
            ),
        ),
        migrations.AlterField(
            model_name="caregiverworkpreferences",
            name="service_specific_answers",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="دیکشنری {نوع خدمت: {نام فیلد: مقدار}} — سوالات فرم ۲ که فقط برای یک نوع خدمت خاص (امور منزل، مادریار، پرستار، بهیار) معنا دارند. سالمندیار سوال اضافه\u200cای در این فرم ندارد چون همان فیلدهای بالا، از ابتدا، مخصوص آن بوده\u200cاند. وقتی چند نوع خدمت هم\u200cزمان انتخاب شده باشد، هر کدام کلید جدا خودش را در این دیکشنری دارد — یکی جای دیگری را پاک نمی\u200cکند.",
                verbose_name="پاسخ\u200cهای فرم ۲ مخصوص نوع خدمت",
            ),
        ),
    ]
