# Generated by Django 5.2.17 on 2026-10-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caregivers", "0030_merge_koodakyar_into_madaryar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="identityprofile",
            name="birth_certificate_issue_city",
        ),
        migrations.RemoveField(
            model_name="identityprofile",
            name="birth_certificate_issue_province",
        ),
        migrations.AlterField(
            model_name="identityprofile",
            name="birth_certificate_issue_place",
            field=models.CharField(
                blank=True,
                max_length=150,
                verbose_name="محل صدور شناسنامه (قدیمی، بدون استفاده)",
            ),
        ),
    ]
