# Generated by Django 5.2.17 on 2026-10-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caregivers", "0031_remove_birth_certificate_issue_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="identityprofile",
            name="age",
            field=models.PositiveSmallIntegerField(
                blank=True, editable=False, null=True, verbose_name="سن"
            ),
        ),
        migrations.AddField(
            model_name="identityprofile",
            name="ethnicity_details",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="زیرگروه قومیت"
            ),
        ),
    ]
