# Generated by Django 5.2.17 on 2026-10-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caregivers", "0033_migrate_ethnicity_and_backfill_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="identityprofile",
            name="child_accompany_at_work",
            field=models.CharField(
                blank=True,
                choices=[("yes", "بله"), ("no", "خیر"), ("indifferent", "فرقی ندارد")],
                help_text="فقط وقتی currently_caring_for_own_child=True معنا دارد؛ در غیر این صورت خالی ذخیره می\u200cشود.",
                max_length=20,
                verbose_name="مایل است هنگام کار فرزندش همراهش باشد؟",
            ),
        ),
    ]
