# Generated by Django 5.2.17 on 2026-10-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caregivers", "0035_remove_ethnicities_tat_assyrian_jewish"),
    ]

    operations = [
        migrations.AddField(
            model_name="identityprofile",
            name="nationality_country_other",
            field=models.CharField(
                blank=True,
                help_text="فقط وقتی nationality_country=other.",
                max_length=100,
                verbose_name="کشور (سایر)",
            ),
        ),
        migrations.AlterField(
            model_name="identityprofile",
            name="nationality_country",
            field=models.CharField(
                blank=True,
                choices=[
                    ("afghanistan", "افغانستان"),
                    ("pakistan", "پاکستان"),
                    ("iraq", "عراق"),
                    ("syria", "سوریه"),
                    ("lebanon", "لبنان"),
                    ("turkmenistan", "ترکمنستان"),
                    ("azerbaijan", "آذربایجان"),
                    ("tajikistan", "تاجیکستان"),
                    ("turkey", "ترکیه"),
                    ("other", "سایر"),
                ],
                help_text="فقط در صورت تابعیت غیرایرانی. «سایر» ⇒ nationality_country_other.",
                max_length=100,
                verbose_name="اهل کدام کشور است",
            ),
        ),
    ]
