# Generated by Django 5.2.17 on 2026-10-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caregivers", "0037_map_nationality_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="caregiverworkpreferences",
            name="collaboration_schedule",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="برنامه\u200cی زمانی نوع همکاری"
            ),
        ),
        migrations.AddField(
            model_name="caregiverworkpreferences",
            name="requested_salary_range",
            field=models.CharField(
                blank=True,
                choices=[
                    ("under_10", "تا ۱۰ میلیون تومان"),
                    ("10_15", "۱۰ تا ۱۵ میلیون تومان"),
                    ("15_20", "۱۵ تا ۲۰ میلیون تومان"),
                    ("20_25", "۲۰ تا ۲۵ میلیون تومان"),
                    ("25_30", "۲۵ تا ۳۰ میلیون تومان"),
                    ("30_40", "۳۰ تا ۴۰ میلیون تومان"),
                    ("over_40", "بیش از ۴۰ میلیون تومان"),
                    ("negotiable", "توافقی"),
                ],
                max_length=20,
                verbose_name="بازه\u200cی حقوق درخواستی",
            ),
        ),
        migrations.AlterField(
            model_name="caregiverworkpreferences",
            name="requested_salary",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="حقوق درخواستی (متن قدیمی)"
            ),
        ),
        migrations.AlterField(
            model_name="caregiverworkpreferences",
            name="work_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full_time", "تمام\u200cوقت"),
                    ("part_time", "پاره\u200cوقت"),
                    ("both", "هر دو مورد"),
                ],
                max_length=20,
                verbose_name="وضعیت کاری (قدیمی، بدون استفاده)",
            ),
        ),
    ]
