# Generated by Django 5.2.17 on 2026-10-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caregivers", "0039_map_collaboration_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="identityprofile",
            name="special_talents",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="فهرستی از مقادیر SpecialTalent؛ در پروفایل نمایش داده می\u200cشود.",
                verbose_name="استعدادها و مهارت\u200cهای ویژه",
            ),
        ),
        migrations.AddField(
            model_name="identityprofile",
            name="special_talents_other",
            field=models.CharField(
                blank=True,
                help_text="فقط وقتی 'other' در special_talents باشد معنا دارد.",
                max_length=200,
                verbose_name="سایر استعدادها",
            ),
        ),
    ]
