# Generated by Django 5.2.17 on 2026-10-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caregivers", "0041_merge_behyar_into_parastar"),
    ]

    operations = [
        migrations.AddField(
            model_name="caregivercompatibilityquestionnaire",
            name="trait_profiles",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="نتیجه\u200cی امتیازدهی سوال\u200cهای موقعیتی (غیرمستقیم)، محاسبه\u200cشده در پنل (مدل\u200cهای lib/trait-model*.ts) و هنگام ذخیره\u200cی پرسشنامه همراه آن ذخیره می\u200cشود: لیستی از {id, title, traits: [{key, label, percent, questions}]} برای هر نقش/زیرشاخه. سبک مراقب را نشان می\u200cدهد، نه توان مطلق او.",
                verbose_name="پروفایل پارامترهای سوال\u200cهای موقعیتی",
            ),
        ),
    ]
