# Generated by Django 6.0.7 on 2026-07-29 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('display_name', models.CharField(max_length=150)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('full_name', models.CharField(help_text='نام و نام خانوادگی سالمند', max_length=150)),
                ('father_name', models.CharField(blank=True, help_text='نام پدر', max_length=150)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('national_id', models.CharField(blank=True, help_text='شماره ملی', max_length=10)),
                ('birth_certificate_number', models.CharField(blank=True, help_text='شماره شناسنامه', max_length=30)),
                ('birth_certificate_issue_place', models.CharField(blank=True, help_text='محل صدور شناسنامه', max_length=150)),
                ('full_address', models.TextField(blank=True, help_text='نشانی کامل محل سکونت (شهر، خیابان، پلاک، واحد)')),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('emergency_contact_phone', models.CharField(blank=True, help_text='شماره تماس اضطراری یکی از اعضای خانواده یا سرپرست', max_length=15)),
                ('guardianship_status', models.CharField(choices=[('none', 'ندارد'), ('legal_guardian', 'قیم قانونی دارد'), ('trustee', 'وصی دارد')], default='none', help_text='وضعیت حقوقی/سرپرستی — آیا وصی یا قیم قانونی دارد؟', max_length=20)),
                ('guardian_details', models.TextField(blank=True, help_text='نام/اطلاعات تماس وصی یا قیم قانونی، در صورت وجود')),
                ('language_dialect', models.CharField(blank=True, help_text='زبان و گویش', max_length=100)),
                ('basic_medical_info', models.TextField(blank=True, help_text='اطلاعات پزشکی پایه — بیماری\u200cهای مهم و نیازهای ویژه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientCompatibilityQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('religious_beliefs_priority', models.CharField(choices=[('strongly_agree', 'کاملاً موافقم'), ('somewhat_agree', 'تاحدی موافق'), ('somewhat_disagree', 'تاحدی مخالف'), ('strongly_disagree', 'کاملاً مخالف')], max_length=20)),
                ('new_treatment_openness', models.CharField(choices=[('very_high', 'خیلی زیاد'), ('moderate', 'نسبتاً'), ('low', 'کم'), ('none', 'اصلاً')], max_length=20)),
                ('caregiver_as_family_member', models.CharField(choices=[('yes', 'بله'), ('no', 'خیر'), ('partially', 'تاحدی')], max_length=20)),
                ('respectful_disagreement_acceptance', models.CharField(choices=[('fully_accept', 'کاملاً می\u200cپذیرم'), ('mostly_accept', 'نسبتاً می\u200cپذیرم'), ('reluctantly_accept', 'به سختی می\u200cپذیرم'), ('reject', 'قطعاً رد می\u200cکنم')], max_length=20)),
                ('privacy_comfort_with_caregiver', models.CharField(choices=[('yes', 'بله'), ('no', 'خیر'), ('partially', 'تاحدی')], max_length=20)),
                ('noise_smell_sensitivity', models.CharField(choices=[('very_high', 'خیلی زیاد'), ('moderate', 'نسبتاً'), ('low', 'کم'), ('none', 'اصلاً')], max_length=20)),
                ('meal_time_strictness', models.CharField(choices=[('very_high', 'خیلی زیاد'), ('moderate', 'نسبتاً'), ('low', 'کم'), ('none', 'اصلاً')], help_text='⚠️ گزینه\u200cهای دقیق در سند منبع مشخص نشده بود — placeholder، نیاز به تأیید محصول', max_length=20)),
                ('special_diet_preference', models.CharField(choices=[('yes', 'بله'), ('no', 'خیر'), ('partially', 'تاحدی')], max_length=20)),
                ('medication_timing_priority', models.CharField(choices=[('very_high', 'خیلی زیاد'), ('moderate', 'نسبتاً'), ('low', 'کم'), ('none', 'اصلاً')], help_text='⚠️ گزینه\u200cهای دقیق در سند منبع مشخص نشده بود — placeholder، نیاز به تأیید محصول', max_length=20)),
                ('accent_customs_annoyance', models.CharField(choices=[('not_at_all', 'اصلاً'), ('slightly', 'کمی'), ('a_lot', 'زیاد'), ('very_much', 'خیلی زیاد')], max_length=20)),
                ('cultural_respect_expectation', models.CharField(choices=[('yes', 'بله'), ('no', 'خیر'), ('partially', 'تاحدی')], max_length=20)),
                ('willingness_to_express_opinion', models.CharField(choices=[('very_high', 'خیلی زیاد'), ('moderate', 'نسبتاً'), ('low', 'کم'), ('none', 'اصلاً')], help_text='⚠️ گزینه\u200cهای دقیق در سند منبع مشخص نشده بود — placeholder، نیاز به تأیید محصول', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_questionnaire', to='families.patientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyPatientLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(help_text='نسبت، مثلاً فرزند/همسر/سرپرست', max_length=50)),
                ('is_primary_contact', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_links', to='families.familyprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_links', to='families.patientprofile')),
            ],
            options={
                'unique_together': {('family', 'patient')},
            },
        ),
    ]
