# Generated by Django 6.0.7 on 2026-08-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(choices=[('user_registered', 'ثبت\u200cنام کاربر'), ('login_success', 'ورود موفق'), ('login_failed', 'تلاش ورود ناموفق'), ('login_locked', 'قفل\u200cشدن حساب پس از تلاش\u200cهای ناموفق'), ('logout', 'خروج'), ('role_changed', 'تغییر نقش کاربر'), ('otp_requested', 'درخواست کد تأیید'), ('otp_verified', 'تأیید موفق کد'), ('otp_failed', 'تلاش ناموفق تأیید کد'), ('password_reset_requested', 'درخواست بازیابی رمز عبور'), ('password_reset_completed', 'تکمیل بازیابی رمز عبور'), ('caregiver_created', 'ثبت مراقب توسط ناظر'), ('caregiver_updated', 'ویرایش اطلاعات مراقب توسط ناظر'), ('caregiver_deleted', 'حذف مراقب توسط ناظر')], max_length=40),
        ),
    ]
