from django.urls import path
from . import views

urlpatterns = [
    path('',          views.index_view,name="home"),
    path('login/',    views.login_view,name="login"),
    path('clinic/',   views.clinic_view,name="clinic"),
    path('bookings/', views.bookings_view,name="bookings"),
    path('wallet/',   views.wallet_view,name="wallet"),
    path('profile/',  views.profile_view,name="profile"),
    path('redemption/', views.redemption_view),
    path('explore/', views.explore_view),
    path('vendor-register/',  views.vendor_register_view),
    path('vendor-dashboard/', views.vendor_dashboard_view),
    path('marketer-register/', views.marketer_register_view),
    path('advisors/', views.advisors_view),
    path('notifications/', views.notifications_view),
    path('support/', views.support_view),
    path('commission-requests/', views.commission_requests_view),
    path('terms/', views.terms_view),
    path('about/', views.about_view),
    path('marketer-dashboard/', views.marketer_dashboard_view),
    path('doctor-register/', views.doctor_register_view),
    path('doctor-dashboard/', views.doctor_dashboard_view),
    path('doctor/', views.doctor_view),
    path('doctor-appointments/', views.doctor_appointments_view),
    path('doctor-chat/', views.doctor_chat_view),
    path('store-register/', views.store_register_view),
    path('store-dashboard/', views.store_dashboard_view),
    path('store/', views.store_view),
    path('orders/', views.orders_view),
    path('admin-panel/',            views.admin_dashboard_view),
    path('admin-panel/clinics/',    views.admin_clinics_view),
    path('admin-panel/categories/', views.admin_categories_view),
    path('admin-panel/users/',      views.admin_users_view),
    path('admin-panel/bookings/',   views.admin_bookings_view),
    path('admin-panel/stores/',     views.admin_stores_view),
    path('admin-panel/bulk-upload/', views.admin_bulk_upload_view),
    path('admin-panel/doctors/',    views.admin_doctors_view),
    path('admin-panel/redemption/', views.admin_redemption_view),
]