# Generated by Django 5.2.17 on 2026-09-26 06:21

import django.core.validators
import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agencies", "0008_agencyadmin_position_agencysupervisor_position"),
        ("care", "0005_caregiverassignment_billing_cycle_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("daily", "روزانه"),
                            ("weekly", "هفتگی"),
                            ("monthly", "ماهانه"),
                        ],
                        max_length=10,
                        verbose_name="دوره صورت\u200cحساب",
                    ),
                ),
                (
                    "period_start",
                    django_jalali.db.models.jDateField(verbose_name="شروع دوره"),
                ),
                (
                    "period_end",
                    django_jalali.db.models.jDateField(verbose_name="پایان دوره"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="مبلغ (تومان)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("issued", "صادرشده"),
                            ("partially_paid", "بخشی پرداخت\u200cشده"),
                            ("paid", "پرداخت\u200cشده"),
                            ("overdue", "معوق"),
                            ("cancelled", "لغوشده"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "due_date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="سررسید"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="یادداشت")),
                (
                    "created_at",
                    django_jalali.db.models.jDateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ایجاد"
                    ),
                ),
                (
                    "updated_at",
                    django_jalali.db.models.jDateTimeField(
                        auto_now=True, verbose_name="تاریخ بروزرسانی"
                    ),
                ),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="agencies.agencyprofile",
                        verbose_name="آژانس",
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="care.caregiverassignment",
                        verbose_name="تخصیص",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_invoices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ایجادکننده",
                    ),
                ),
            ],
            options={
                "verbose_name": "صورت\u200cحساب",
                "verbose_name_plural": "صورت\u200cحساب\u200cها",
                "ordering": ["-period_start", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="مبلغ (تومان)",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "نقدی"),
                            ("card_transfer", "کارت\u200cبه\u200cکارت"),
                            ("bank_transfer", "حواله بانکی"),
                            ("online", "پرداخت آنلاین"),
                            ("cheque", "چک"),
                            ("other", "سایر"),
                        ],
                        default="cash",
                        max_length=20,
                        verbose_name="روش پرداخت",
                    ),
                ),
                (
                    "paid_at",
                    django_jalali.db.models.jDateField(verbose_name="تاریخ پرداخت"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="یادداشت")),
                (
                    "created_at",
                    django_jalali.db.models.jDateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ثبت"
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="finance.invoice",
                        verbose_name="صورت\u200cحساب",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ثبت\u200cکننده",
                    ),
                ),
            ],
            options={
                "verbose_name": "پرداخت",
                "verbose_name_plural": "پرداخت\u200cها",
                "ordering": ["-paid_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceTariff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("daily", "مراقبت روزانه"),
                            ("night", "مراقبت شبانه"),
                            ("live_in", "مراقبت شبانه\u200cروزی (مقیم)"),
                            ("hospital_companion", "همراه سالمند در بیمارستان"),
                            ("home_companion", "همراه سالمند در منزل"),
                            ("short_term", "مراقبت موقت (چند روزه)"),
                            ("long_term", "مراقبت بلندمدت"),
                        ],
                        max_length=30,
                        verbose_name="نوع خدمت",
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="نرخ ساعتی (تومان)",
                    ),
                ),
                (
                    "daily_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="نرخ روزانه (تومان)",
                    ),
                ),
                (
                    "monthly_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="نرخ ماهانه (تومان)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    django_jalali.db.models.jDateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ایجاد"
                    ),
                ),
                (
                    "updated_at",
                    django_jalali.db.models.jDateTimeField(
                        auto_now=True, verbose_name="تاریخ بروزرسانی"
                    ),
                ),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tariffs",
                        to="agencies.agencyprofile",
                        verbose_name="آژانس",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tariffs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ایجادکننده",
                    ),
                ),
            ],
            options={
                "verbose_name": "تعرفه خدمت",
                "verbose_name_plural": "تعرفه\u200cهای خدمت",
                "ordering": ["service_type"],
                "unique_together": {("agency", "service_type")},
            },
        ),
    ]
