# Generated by Django 5.2.17 on 2026-09-26 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("care", "0005_caregiverassignment_billing_cycle_and_more"),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="care.caregiverassignment",
                verbose_name="تخصیص",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="period_type",
            field=models.CharField(
                choices=[
                    ("daily", "روزانه"),
                    ("weekly", "هفتگی"),
                    ("monthly", "ماهانه"),
                    ("one_off", "مقطعی"),
                ],
                max_length=10,
                verbose_name="دوره صورت\u200cحساب",
            ),
        ),
    ]
