# Generated by Django 6.0.7 on 2026-07-29 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=150)),
                ('birth_certificate_number', models.CharField(max_length=30)),
                ('birth_certificate_issue_place', models.CharField(max_length=150)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('female', 'زن'), ('male', 'مرد')], max_length=10)),
                ('marital_status', models.CharField(choices=[('single', 'مجرد'), ('married', 'متأهل'), ('divorced', 'مطلقه'), ('widowed', 'همسر فوت شده')], max_length=20)),
                ('children_count', models.CharField(choices=[('none', 'بدون فرزند'), ('one', '۱'), ('two', '۲'), ('three', '۳'), ('four_or_more', '۴ یا بیشتر')], max_length=20)),
                ('military_status', models.CharField(blank=True, choices=[('completed', 'پایان خدمت'), ('permanent_exemption', 'معافیت دائم'), ('temporary_exemption', 'معافیت موقت'), ('in_service', 'در حال خدمت')], help_text='فقط برای جنسیت مرد — برای زن باید خالی بماند', max_length=30, null=True)),
                ('height_range', models.CharField(blank=True, choices=[('under_150', 'کمتر از ۱۵۰'), ('150_160', '۱۵۰–۱۶۰'), ('160_170', '۱۶۰–۱۷۰'), ('170_180', '۱۷۰–۱۸۰'), ('over_180', 'بالاتر از ۱۸۰')], max_length=20)),
                ('weight_range', models.CharField(blank=True, choices=[('under_50', 'کمتر از ۵۰'), ('50_60', '۵۰–۶۰'), ('60_70', '۶۰–۷۰'), ('70_80', '۷۰–۸۰'), ('80_90', '۸۰–۹۰'), ('over_90', 'بالاتر از ۹۰')], max_length=20)),
                ('ethnicities', models.JSONField(blank=True, default=list, help_text='چندانتخابی — لیستی از مقادیر Ethnicity')),
                ('has_chronic_disease', models.BooleanField()),
                ('chronic_disease_types', models.JSONField(blank=True, default=list)),
                ('takes_permanent_medication', models.BooleanField(default=False)),
                ('medication_types', models.JSONField(blank=True, default=list)),
                ('emergency_contact_phone', models.CharField(max_length=15)),
                ('emergency_contact_relation', models.CharField(choices=[('spouse', 'همسر'), ('father', 'پدر'), ('mother', 'مادر'), ('child', 'فرزند'), ('sister', 'خواهر'), ('brother', 'برادر'), ('other', 'سایر')], max_length=20)),
                ('landline_phone', models.CharField(blank=True, max_length=15)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('full_address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
