# Generated by Django 6.0.7 on 2026-08-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterField(
            model_name='user',
            name='is_phone_verified',
            field=models.BooleanField(default=False, verbose_name='تأیید شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='شناسه ملی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text='شماره موبایل (با کد کشور، بدون صفر اول)', max_length=15, unique=True, verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superuser', 'سوپریوزر'), ('admin', 'ادمین / کارشناس'), ('agency', 'آژانس / شرکت'), ('family', 'خانواده'), ('patient', 'بیمار / سالمند'), ('caregiver', 'مراقب')], default='family', max_length=20, verbose_name='نقش'),
        ),
    ]
