# Generated by Django 6.0.7 on 2026-07-31 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_identityprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identityprofile',
            options={'verbose_name': 'پروفایل هویتی', 'verbose_name_plural': 'پروفایل\u200cهای هویتی'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterField(
            model_name='identityprofile',
            name='birth_certificate_issue_place',
            field=models.CharField(max_length=150, verbose_name='محل صدور گواهی تولد'),
        ),
        migrations.AlterField(
            model_name='identityprofile',
            name='birth_certificate_number',
            field=models.CharField(max_length=30, verbose_name='شماره گواهی تولد'),
        ),
        migrations.AlterField(
            model_name='identityprofile',
            name='birth_date',
            field=models.DateField(verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='identityprofile',
            name='children_count',
            field=models.CharField(choices=[('none', 'بدون فرزند'), ('one', '۱'), ('two', '۲'), ('three', '۳'), ('four_or_more', '۴ یا بیشتر')], max_length=20, verbose_name='تعداد فرزندان'),
        ),
        migrations.AlterField(
            model_name='identityprofile',
            name='chronic_disease_types',
            field=models.JSONField(blank=True, default=list, verbose_name='انواع بیماری\u200cهای مزمن'),
        ),
        migrations.AlterField(
            model_name='identityprofile',
            name='city',
            field=models.CharField(max_length=100, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='identityprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='identityprofile',
            name='district',
            field=models.CharField(max_length=100, verbose_name='منطقه'),
        ),
        migrations.AlterField(
            model_name='identityprofile',
            name='emergency_contact_phone',
            field=models.CharField(max_length=15, verbose_name='شماره تماس اضطراری'),
        ),
        migrations.AlterField(
            model_name='identityprofile',
            name='emergency_contact_relation',
            field=models.CharField(choices=[('spouse', 'همسر'), ('father', 'پدر'), ('mother', 'مادر'), ('child', 'فرزند'), ('sister', 'خواهر'), ('brother', 'برادر'), ('other', 'سایر')], max_length=20, verbose_name='نسبت به تماس اضطراری'),
        ),
        migrations.AlterField(
            model_name='identityprofile',
            name='ethnicities',
            field=models.JSONField(blank=True, default=list, help_text='چندانتخابی — لیستی از مقادیر Ethnicity', verbose_name='اقليت\u200cها'),
        ),
        migrations.AlterField(
            model_name='identityprofile',
            name='father_name',
            field=models.CharField(max_length=150, verbose_name='نام پدر'),
        ),
        migrations.AlterField(
            model_name='identityprofile',
            name='full_address',
            field=models.TextField(verbose_name='آدرس کامل'),
        ),
        migrations.AlterField(
            model_name='identityprofile',
            name='gender',
            field=models.CharField(choices=[('female', 'زن'), ('male', 'مرد')], max_length=10, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='identityprofile',
            name='has_chronic_disease',
            field=models.BooleanField(verbose_name='آیا بیماری مزمن دارید?'),
        ),
        migrations.AlterField(
            model_name='identityprofile',
            name='height_range',
            field=models.CharField(blank=True, choices=[('under_150', 'کمتر از ۱۵۰'), ('150_160', '۱۵۰–۱۶۰'), ('160_170', '۱۶۰–۱۷۰'), ('170_180', '۱۷۰–۱۸۰'), ('over_180', 'بالاتر از ۱۸۰')], max_length=20, verbose_name='محدوده قد'),
        ),
        migrations.AlterField(
            model_name='identityprofile',
            name='landline_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='شماره تلفن ثابت'),
        ),
        migrations.AlterField(
            model_name='identityprofile',
            name='marital_status',
            field=models.CharField(choices=[('single', 'مجرد'), ('married', 'متأهل'), ('divorced', 'مطلقه'), ('widowed', 'همسر فوت شده')], max_length=20, verbose_name='وضعیت تاهل'),
        ),
        migrations.AlterField(
            model_name='identityprofile',
            name='medication_types',
            field=models.JSONField(blank=True, default=list, verbose_name='انواع داروها'),
        ),
        migrations.AlterField(
            model_name='identityprofile',
            name='military_status',
            field=models.CharField(blank=True, choices=[('completed', 'پایان خدمت'), ('permanent_exemption', 'معافیت دائم'), ('temporary_exemption', 'معافیت موقت'), ('in_service', 'در حال خدمت')], help_text='فقط برای جنسیت مرد — برای زن باید خالی بماند', max_length=30, null=True, verbose_name='وضعیت نظام وظیفه'),
        ),
        migrations.AlterField(
            model_name='identityprofile',
            name='postal_code',
            field=models.CharField(max_length=10, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='identityprofile',
            name='province',
            field=models.CharField(max_length=100, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='identityprofile',
            name='takes_permanent_medication',
            field=models.BooleanField(default=False, verbose_name='آیا داروی دائمی مصرف می\u200cکنید?'),
        ),
        migrations.AlterField(
            model_name='identityprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ و زمان بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='identityprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity_profile', to=settings.AUTH_USER_MODEL, verbose_name='پروفایل هویتی'),
        ),
        migrations.AlterField(
            model_name='identityprofile',
            name='weight_range',
            field=models.CharField(blank=True, choices=[('under_50', 'کمتر از ۵۰'), ('50_60', '۵۰–۶۰'), ('60_70', '۶۰–۷۰'), ('70_80', '۷۰–۸۰'), ('80_90', '۸۰–۹۰'), ('over_90', 'بالاتر از ۹۰')], max_length=20, verbose_name='محدوده وزن'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_phone_verified',
            field=models.BooleanField(default=False, verbose_name='تأیید شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='شناسه ملی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text='شماره موبایل (با کد کشور، بدون صفر اول)', max_length=15, unique=True, verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superuser', 'سوپریوزر'), ('admin', 'ادمین / کارشناس'), ('agency', 'آژانس / شرکت'), ('family', 'خانواده'), ('patient', 'بیمار / سالمند'), ('caregiver', 'مراقب')], default='family', max_length=20, verbose_name='نقش'),
        ),
    ]
