# Generated by Django 6.0.7 on 2026-08-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('superuser', 'سوپریوزر'),
                    ('admin', 'ادمین / کارشناس'),
                    ('agency', 'آژانس / شرکت'),
                    ('agency_supervisor', 'سوپروایزر آژانس'),
                    ('family', 'خانواده'),
                    ('patient', 'بیمار / سالمند'),
                    ('caregiver', 'مراقب'),
                ],
                default='family', max_length=20, verbose_name='نقش',
            ),
        ),
    ]
