# Generated by Django 6.0.7 on 2026-09-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("superuser", "سوپریوزر"),
                    ("admin", "ادمین / کارشناس"),
                    ("agency", "آژانس / شرکت"),
                    ("agency_supervisor", "سوپروایزر آژانس"),
                    ("agency_admin", "ادمین آژانس"),
                    ("agency_other", "سایر پرسنل آژانس"),
                    ("family", "خانواده"),
                    ("patient", "بیمار / سالمند"),
                    ("caregiver", "مراقب"),
                ],
                default="family",
                max_length=20,
                verbose_name="نقش",
            ),
        ),
    ]
