# Generated by Django 5.2.17 on 2026-09-26 11:35

import django.core.validators
import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agencies", "0008_agencyadmin_position_agencysupervisor_position"),
        ("caregivers", "0015_caregiverprofile_process_milestones_and_more"),
        ("finance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EpisodicReminderRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anchor_stage",
                    models.CharField(
                        choices=[
                            ("phone_coordination", "هماهنگی تلفنی"),
                            ("dispatched", "اعزام"),
                            ("settled", "تسویه\u200cحساب"),
                            ("followup", "پیگیری"),
                        ],
                        help_text="شمارش روزها از لحظه\u200cی ورود کارت به این مرحله شروع می\u200cشود.",
                        max_length=30,
                        verbose_name="مبنای شمارش روز",
                    ),
                ),
                (
                    "display_stage",
                    models.CharField(
                        choices=[
                            ("phone_coordination", "هماهنگی تلفنی"),
                            ("dispatched", "اعزام"),
                            ("settled", "تسویه\u200cحساب"),
                            ("followup", "پیگیری"),
                        ],
                        help_text="یادآوری فقط زمانی روی کارت نشان داده می\u200cشود که کارت هم\u200cاکنون در این مرحله باشد.",
                        max_length=30,
                        verbose_name="نمایش در مرحله",
                    ),
                ),
                (
                    "days_threshold",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="تعداد روز",
                    ),
                ),
                ("label", models.CharField(max_length=100, verbose_name="متن یادآوری")),
                (
                    "color",
                    models.CharField(
                        choices=[("red", "قرمز"), ("amber", "زرد"), ("blue", "آبی")],
                        default="red",
                        max_length=10,
                        verbose_name="رنگ",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    django_jalali.db.models.jDateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ایجاد"
                    ),
                ),
                (
                    "updated_at",
                    django_jalali.db.models.jDateTimeField(
                        auto_now=True, verbose_name="تاریخ بروزرسانی"
                    ),
                ),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodic_reminder_rules",
                        to="agencies.agencyprofile",
                        verbose_name="آژانس",
                    ),
                ),
            ],
            options={
                "verbose_name": "قانون یادآوری خدمات مقطعی",
                "verbose_name_plural": "قوانین یادآوری خدمات مقطعی",
                "ordering": ["display_stage", "days_threshold"],
            },
        ),
        migrations.CreateModel(
            name="EpisodicService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipient_full_name",
                    models.CharField(
                        max_length=150, verbose_name="نام خدمت\u200cگیرنده"
                    ),
                ),
                (
                    "recipient_phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="شماره تماس خدمت\u200cگیرنده",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="یادداشت")),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("phone_coordination", "هماهنگی تلفنی"),
                            ("dispatched", "اعزام"),
                            ("settled", "تسویه\u200cحساب"),
                            ("followup", "پیگیری"),
                        ],
                        db_index=True,
                        default="phone_coordination",
                        max_length=30,
                        verbose_name="مرحله",
                    ),
                ),
                (
                    "phone_coordination_at",
                    django_jalali.db.models.jDateTimeField(
                        blank=True, null=True, verbose_name="زمان ورود به هماهنگی تلفنی"
                    ),
                ),
                (
                    "dispatched_at",
                    django_jalali.db.models.jDateTimeField(
                        blank=True, null=True, verbose_name="زمان اعزام"
                    ),
                ),
                (
                    "settled_at",
                    django_jalali.db.models.jDateTimeField(
                        blank=True, null=True, verbose_name="زمان تسویه\u200cحساب"
                    ),
                ),
                (
                    "followup_at",
                    django_jalali.db.models.jDateTimeField(
                        blank=True, null=True, verbose_name="زمان ورود به پیگیری"
                    ),
                ),
                (
                    "created_at",
                    django_jalali.db.models.jDateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ایجاد"
                    ),
                ),
                (
                    "updated_at",
                    django_jalali.db.models.jDateTimeField(
                        auto_now=True, verbose_name="تاریخ بروزرسانی"
                    ),
                ),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodic_services",
                        to="agencies.agencyprofile",
                        verbose_name="آژانس",
                    ),
                ),
                (
                    "assigned_caregiver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="episodic_dispatches",
                        to="caregivers.caregiverprofile",
                        verbose_name="مراقب اعزامی",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_episodic_services",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ثبت\u200cکننده",
                    ),
                ),
                (
                    "invoice",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="episodic_service",
                        to="finance.invoice",
                        verbose_name="فاکتور",
                    ),
                ),
            ],
            options={
                "verbose_name": "خدمت مقطعی",
                "verbose_name_plural": "خدمات مقطعی",
                "ordering": ["-created_at"],
            },
        ),
    ]
