# Generated by Django 5.2.17 on 2026-09-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodic", "0003_remove_reminder_rule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episodicservice",
            name="stage",
            field=models.CharField(
                db_index=True,
                default="phone_coordination",
                max_length=30,
                verbose_name="مرحله",
            ),
        ),
    ]
