export const ROUTES = {
  login: "/login",
  dashboard: "/dashboard",
  families: "/families",
  caregivers: "/caregivers",
  supervisors: "/supervisors",
  patients: "/patients",
  patientMatch: (patientId: number) => `/patients/${patientId}/match`,
  complaints: "/complaints",
  blacklistAppeals: "/blacklist-appeals",
  candidates: "/candidates",
  matching: "/matching",
  analytics: "/analytics",
  financial: "/financial",
  settings: "/settings",
  admins: "/admins",
}
