# Generated by Django 6.0.7 on 2026-07-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('user_registered', 'ثبت\u200cنام کاربر'), ('login_success', 'ورود موفق'), ('login_failed', 'تلاش ورود ناموفق'), ('login_locked', 'قفل\u200cشدن حساب پس از تلاش\u200cهای ناموفق'), ('logout', 'خروج'), ('role_changed', 'تغییر نقش کاربر'), ('otp_requested', 'درخواست کد تأیید'), ('otp_verified', 'تأیید موفق کد'), ('otp_failed', 'تلاش ناموفق تأیید کد'), ('password_reset_requested', 'درخواست بازیابی رمز عبور'), ('password_reset_completed', 'تکمیل بازیابی رمز عبور')], max_length=40)),
                ('actor_user_id', models.PositiveIntegerField(blank=True, help_text='کاربری که این رویداد را ایجاد کرده — ممکن است ناشناس باشد (مثلاً تلاش ورود ناموفق)', null=True)),
                ('target_user_id', models.PositiveIntegerField(blank=True, help_text='کاربری که رویداد روی او اثر گذاشته — در بیشتر موارد همان actor است', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='audit_audit_event_t_ac78f0_idx'), models.Index(fields=['target_user_id', 'created_at'], name='audit_audit_target__514ec6_idx')],
            },
        ),
    ]
