# Generated by Django 6.0.7 on 2026-08-02 10:14

from django.db import migrations

def create_provinces(apps, schema_editor):
    Province = apps.get_model("locations", "Province")

    Province.objects.create(name="آذربایجان شرقی")
    Province.objects.create(name="آذربایجان غربی")
    Province.objects.create(name="اردبیل")
    Province.objects.create(name="اصفهان")
    Province.objects.create(name="البرز")
    Province.objects.create(name="ایلام")
    Province.objects.create(name="بوشهر")
    Province.objects.create(name="تهران")
    Province.objects.create(name="چهارمحال و بختیاری")
    Province.objects.create(name="خراسان جنوبی")
    Province.objects.create(name="خراسان رضوی")
    Province.objects.create(name="خراسان شمالی")
    Province.objects.create(name="خوزستان")
    Province.objects.create(name="زنجان")
    Province.objects.create(name="سمنان")
    Province.objects.create(name="سیستان و بلوچستان")
    Province.objects.create(name="فارس")
    Province.objects.create(name="قزوین")
    Province.objects.create(name="قم")
    Province.objects.create(name="کردستان")
    Province.objects.create(name="کرمان")
    Province.objects.create(name="کرمانشاه")
    Province.objects.create(name="کهگیلویه و بویراحمد")
    Province.objects.create(name="گلستان")
    Province.objects.create(name="گیلان")
    Province.objects.create(name="لرستان")
    Province.objects.create(name="مازندران")
    Province.objects.create(name="مرکزی")
    Province.objects.create(name="هرمزگان")
    Province.objects.create(name="همدان")
    Province.objects.create(name="یزد")

class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_provinces),

    ]
