# Generated by Django 6.0.7 on 2026-08-02 10:54

from django.db import migrations

def create_tehran_districts(apps, schema_editor):
    City = apps.get_model("locations", "City")
    District = apps.get_model("locations", "District")
    tehran = City.objects.get(
        name="تهران"
    )

    districts = [
        "منطقه ۱",
        "منطقه ۲",
        "منطقه ۳",
        "منطقه ۴",
        "منطقه ۵",
        "منطقه ۶",
        "منطقه ۷",
        "منطقه ۸",
        "منطقه ۹",
        "منطقه ۱۰",
        "منطقه ۱۱",
        "منطقه ۱۲",
        "منطقه ۱۳",
        "منطقه ۱۴",
        "منطقه ۱۵",
        "منطقه ۱۶",
        "منطقه ۱۷",
        "منطقه ۱۸",
        "منطقه ۱۹",
        "منطقه ۲۰",
        "منطقه ۲۱",
        "منطقه ۲۲",
    ]

    District.objects.bulk_create(
        [
            District(
                city=tehran,
                name=district
            )
            for district in districts
        ]
    )



class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0003_auto_20260802_1415"),
    ]

    operations = [
        migrations.RunPython(create_tehran_districts),
    ]
