# Generated by Django 6.0.7 on 2026-08-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0004_auto_20260802_1424"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="district",
            options={"ordering": ["municipality_zone", "name"]},
        ),
        migrations.RemoveConstraint(
            model_name="district",
            name="unique_district_per_city",
        ),
        migrations.AddField(
            model_name="district",
            name="municipality_zone",
            field=models.PositiveSmallIntegerField(
                db_index=True, default=1, verbose_name="منطقه شهرداری"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="district",
            name="name",
            field=models.CharField(max_length=100, verbose_name="محله"),
        ),
    ]
