# Generated by Django 6.0.7 on 2026-08-02 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0006_auto_20260802_1517"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={
                "ordering": ["name"],
                "verbose_name": "شهر",
                "verbose_name_plural": "شهرها",
            },
        ),
        migrations.AlterModelOptions(
            name="district",
            options={
                "ordering": ["municipality_zone", "name"],
                "verbose_name": "محله",
                "verbose_name_plural": "محله\u200cها",
            },
        ),
        migrations.AlterModelOptions(
            name="province",
            options={
                "ordering": ["name"],
                "verbose_name": "استان",
                "verbose_name_plural": "استان\u200cها",
            },
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=100, verbose_name="شهر"),
        ),
        migrations.AlterField(
            model_name="city",
            name="province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="locations.province",
                verbose_name="استان",
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="districts",
                to="locations.city",
                verbose_name="شهر",
            ),
        ),
        migrations.AlterField(
            model_name="province",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="استان"),
        ),
        migrations.AddConstraint(
            model_name="district",
            constraint=models.UniqueConstraint(
                fields=("city", "name"), name="unique_district_per_city"
            ),
        ),
    ]
