# Generated by Django 6.0.7 on 2026-08-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0007_alter_city_options_alter_district_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="province",
            options={
                "ordering": ["ordering_number"],
                "verbose_name": "استان",
                "verbose_name_plural": "استان\u200cها",
            },
        ),
        migrations.RemoveConstraint(
            model_name="district",
            name="unique_district_per_city",
        ),
        migrations.AddField(
            model_name="province",
            name="ordering_number",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="ترتیب نمایش"
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="municipality_zone",
            field=models.PositiveSmallIntegerField(
                blank=True, db_index=True, null=True, verbose_name="منطقه شهرداری"
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="محله"
            ),
        ),
    ]
