# Generated by Django 6.0.7 on 2026-08-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0008_alter_province_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="province",
            name="ordering_number",
            field=models.PositiveSmallIntegerField(
                db_index=True, default=0, verbose_name="ترتیب نمایش"
            ),
        ),
    ]
