# Generated by Django 6.0.7 on 2026-08-23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('families', '0001_initial'),
        ('caregivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='نام شرکت/آژانس')),
                ('license_number', models.CharField(blank=True, max_length=100, verbose_name='شماره مجوز فعالیت')),
                ('access_code', models.CharField(editable=False, help_text='کد یکتا برای درخواست پیوستن خانواده یا مراقب به این آژانس — مثلاً AGN-92K7XQ', max_length=20, unique=True, verbose_name='کد عضویت آژانس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ و زمان بروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agency_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل آژانس',
                'verbose_name_plural': 'پروفایل\u200cهای آژانس',
            },
        ),
        migrations.CreateModel(
            name='AgencyFamilyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('approved', 'تأییدشده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تصمیم')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان درخواست')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_links', to='agencies.agencyprofile', verbose_name='آژانس')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_agency_family_links', to=settings.AUTH_USER_MODEL, verbose_name='تصمیم\u200cگیرنده')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_links', to='families.familyprofile', verbose_name='خانواده')),
            ],
            options={
                'verbose_name': 'ارتباط آژانس و خانواده',
                'verbose_name_plural': 'ارتباط\u200cهای آژانس و خانواده',
                'unique_together': {('agency', 'family')},
            },
        ),
        migrations.CreateModel(
            name='AgencyCaregiverLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('approved', 'تأییدشده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تصمیم')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان درخواست')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_links', to='agencies.agencyprofile', verbose_name='آژانس')),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_links', to='caregivers.caregiverprofile', verbose_name='مراقب')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_agency_caregiver_links', to=settings.AUTH_USER_MODEL, verbose_name='تصمیم\u200cگیرنده')),
            ],
            options={
                'verbose_name': 'ارتباط آژانس و مراقب',
                'verbose_name_plural': 'ارتباط\u200cهای آژانس و مراقب',
                'unique_together': {('agency', 'caregiver')},
            },
        ),
    ]
