# Generated by Django 6.0.7 on 2026-08-23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencySupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisors', to='agencies.agencyprofile', verbose_name='آژانس')),
                ('created_by', models.ForeignKey(blank=True, help_text='خود آژانس این حساب را ساخته، یا یک سوپریوزر — هر دو مجازند.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agency_supervisors', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agency_supervisor_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سوپروایزر آژانس',
                'verbose_name_plural': 'سوپروایزرهای آژانس',
            },
        ),
    ]
