# Generated by Django 6.0.7 on 2026-08-23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agencies', '0002_agencysupervisor'),
        ('families', '0009_patient_care_needs'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyPatientLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('approved', 'تأییدشده'), ('rejected', 'رد شده')], default='approved', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_links', to='agencies.agencyprofile', verbose_name='آژانس')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_agency_patient_links', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_links', to='families.patientprofile', verbose_name='سالمند')),
            ],
            options={
                'verbose_name': 'ارتباط آژانس و سالمند',
                'verbose_name_plural': 'ارتباط\u200cهای آژانس و سالمند',
                'unique_together': {('agency', 'patient')},
            },
        ),
    ]
