# Generated by Django 6.0.7 on 2026-08-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_agencypatientlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyprofile',
            name='isolation_mode',
            field=models.CharField(
                choices=[('shared', 'زیرساخت مشترک'), ('dedicated', 'زیرساخت اختصاصی')],
                default='shared',
                help_text="امروز فقط 'مشترک' دارای پیاده‌سازی واقعی است — این فیلد صرفاً برای آماده‌بودن معماری برای آینده اضافه شده.",
                max_length=20,
                verbose_name='سطح ایزوله\u200cسازی',
            ),
        ),
    ]
