# Generated by Django 6.0.7 on 2026-08-27

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Adds db_index=True to the status field on all three agency link
    tables (AgencyFamilyLink, AgencyCaregiverLink, AgencyPatientLink).

    These are exactly the fields filtered on in every single matching
    query — waterfall.py's status=APPROVED hard filter, and every
    agency-scoped roster/matching query's status=APPROVED filter on
    these three tables — with zero index on any of them until now.
    At small scale this never shows up; at real scale (the whole
    reason this is being fixed now) an unindexed CharField filter on
    a large table forces a full table scan on every single request,
    which is a real, separate performance problem from either N+1
    already found and fixed elsewhere in the matching pipeline.
    """

    dependencies = [
        ('agencies', '0004_agencyprofile_isolation_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyfamilylink',
            name='status',
            field=models.CharField(
                choices=[('pending', 'در انتظار تأیید'), ('approved', 'تأییدشده'), ('rejected', 'رد شده')],
                db_index=True, default='pending', max_length=20, verbose_name='وضعیت',
            ),
        ),
        migrations.AlterField(
            model_name='agencycaregiverlink',
            name='status',
            field=models.CharField(
                choices=[('pending', 'در انتظار تأیید'), ('approved', 'تأییدشده'), ('rejected', 'رد شده')],
                db_index=True, default='pending', max_length=20, verbose_name='وضعیت',
            ),
        ),
        migrations.AlterField(
            model_name='agencypatientlink',
            name='status',
            field=models.CharField(
                choices=[('pending', 'در انتظار تأیید'), ('approved', 'تأییدشده'), ('rejected', 'رد شده')],
                db_index=True, default='approved', max_length=20, verbose_name='وضعیت',
            ),
        ),
    ]
