# Generated by Django 6.0.7 on 2026-08-30 14:20

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agencies", "0005_agency_link_status_db_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agencycaregiverlink",
            name="decided_at",
            field=django_jalali.db.models.jDateTimeField(
                blank=True, null=True, verbose_name="زمان تصمیم"
            ),
        ),
        migrations.AlterField(
            model_name="agencycaregiverlink",
            name="requested_at",
            field=django_jalali.db.models.jDateTimeField(
                auto_now_add=True, verbose_name="زمان درخواست"
            ),
        ),
        migrations.AlterField(
            model_name="agencyfamilylink",
            name="decided_at",
            field=django_jalali.db.models.jDateTimeField(
                blank=True, null=True, verbose_name="زمان تصمیم"
            ),
        ),
        migrations.AlterField(
            model_name="agencyfamilylink",
            name="requested_at",
            field=django_jalali.db.models.jDateTimeField(
                auto_now_add=True, verbose_name="زمان درخواست"
            ),
        ),
        migrations.AlterField(
            model_name="agencypatientlink",
            name="created_at",
            field=django_jalali.db.models.jDateTimeField(
                auto_now_add=True, verbose_name="تاریخ ایجاد"
            ),
        ),
        migrations.AlterField(
            model_name="agencyprofile",
            name="created_at",
            field=django_jalali.db.models.jDateTimeField(
                auto_now_add=True, verbose_name="تاریخ و زمان ایجاد"
            ),
        ),
        migrations.AlterField(
            model_name="agencyprofile",
            name="updated_at",
            field=django_jalali.db.models.jDateTimeField(
                auto_now=True, verbose_name="تاریخ و زمان بروزرسانی"
            ),
        ),
        migrations.AlterField(
            model_name="agencysupervisor",
            name="created_at",
            field=django_jalali.db.models.jDateTimeField(
                auto_now_add=True, verbose_name="تاریخ ایجاد"
            ),
        ),
    ]
