# Generated by Django 6.0.7 on 2026-09-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agencies", "0007_agencyadmin"),
    ]

    operations = [
        migrations.AddField(
            model_name="agencyadmin",
            name="position",
            field=models.CharField(
                blank=True,
                help_text="عنوان دقیق سمت این ادمین در چارت سازمانی آژانس — آزاد، چون چارت هر آژانس فرق دارد.",
                max_length=100,
                verbose_name="سمت",
            ),
        ),
        migrations.AddField(
            model_name="agencysupervisor",
            name="position",
            field=models.CharField(
                blank=True,
                help_text="عنوان دقیق سمت این سوپروایزر در چارت سازمانی آژانس — آزاد، چون چارت هر آژانس فرق دارد.",
                max_length=100,
                verbose_name="سمت",
            ),
        ),
    ]
