# Generated by Django 5.2.17 on 2026-09-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agencies", "0008_agencyadmin_position_agencysupervisor_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="agencyprofile",
            name="admin_finance_access",
            field=models.BooleanField(
                default=False,
                help_text="اگر فعال باشد، ادمین\u200cهای این آژانس هم می\u200cتوانند بخش «مالی» را ببینند و در آن کار کنند — پیش\u200cفرض برای همه آژانس\u200cها خاموش است.",
                verbose_name="دسترسی ادمین\u200cها به بخش مالی",
            ),
        ),
        migrations.AlterField(
            model_name="agencyprofile",
            name="access_code",
            field=models.CharField(
                editable=False,
                help_text="کد یکتا برای درخواست پیوستن خانواده یا مراقب به این آژانس — مثلاً QXK-92K7XQ (پیشوند QXK مخصوص همین آژانس است).",
                max_length=20,
                unique=True,
                verbose_name="کد عضویت آژانس",
            ),
        ),
    ]
