# Generated by Django 5.2.17 on 2026-09-28 06:03

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agencies", "0010_agencyprofile_code_prefix"),
        ("locations", "0009_alter_province_ordering_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="agencyadmin",
            name="birth_date",
            field=django_jalali.db.models.jDateField(
                blank=True, null=True, verbose_name="تاریخ تولد"
            ),
        ),
        migrations.AddField(
            model_name="agencyadmin",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agency_admins",
                to="locations.city",
                verbose_name="شهر",
            ),
        ),
        migrations.AddField(
            model_name="agencyadmin",
            name="education_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("under_diploma", "زیر دیپلم"),
                    ("diploma", "دیپلم"),
                    ("associate", "کاردانی"),
                    ("bachelor", "کارشناسی"),
                    ("master", "کارشناسی ارشد"),
                    ("phd", "دکتری"),
                ],
                max_length=20,
                null=True,
                verbose_name="مدرک تحصیلی",
            ),
        ),
        migrations.AddField(
            model_name="agencyadmin",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("female", "زن"), ("male", "مرد")],
                max_length=10,
                null=True,
                verbose_name="جنسیت",
            ),
        ),
        migrations.AddField(
            model_name="agencysupervisor",
            name="birth_date",
            field=django_jalali.db.models.jDateField(
                blank=True, null=True, verbose_name="تاریخ تولد"
            ),
        ),
        migrations.AddField(
            model_name="agencysupervisor",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agency_supervisors",
                to="locations.city",
                verbose_name="شهر",
            ),
        ),
        migrations.AddField(
            model_name="agencysupervisor",
            name="education_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("under_diploma", "زیر دیپلم"),
                    ("diploma", "دیپلم"),
                    ("associate", "کاردانی"),
                    ("bachelor", "کارشناسی"),
                    ("master", "کارشناسی ارشد"),
                    ("phd", "دکتری"),
                ],
                max_length=20,
                null=True,
                verbose_name="مدرک تحصیلی",
            ),
        ),
        migrations.AddField(
            model_name="agencysupervisor",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("female", "زن"), ("male", "مرد")],
                max_length=10,
                null=True,
                verbose_name="جنسیت",
            ),
        ),
    ]
