# Generated by Django 5.2.17 on 2026-09-29 08:01

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agencies", "0011_agencyadmin_birth_date_agencyadmin_city_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgencyPipelineStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pipeline_type",
                    models.CharField(
                        choices=[
                            ("patient", "کاریز خدمت\u200cگیرنده"),
                            ("caregiver", "کاریز خدمت\u200cدهنده"),
                        ],
                        max_length=10,
                        verbose_name="نوع کاریز",
                    ),
                ),
                (
                    "value",
                    models.SlugField(
                        max_length=40, verbose_name="مقدار ذخیره\u200cشده"
                    ),
                ),
                ("label", models.CharField(max_length=60, verbose_name="عنوان مرحله")),
                ("order", models.PositiveSmallIntegerField(verbose_name="ترتیب نمایش")),
                (
                    "created_at",
                    django_jalali.db.models.jDateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ایجاد"
                    ),
                ),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipeline_stages",
                        to="agencies.agencyprofile",
                        verbose_name="آژانس",
                    ),
                ),
            ],
            options={
                "verbose_name": "مرحله کاریز آژانس",
                "verbose_name_plural": "مراحل کاریز آژانس",
                "ordering": ["pipeline_type", "order"],
                "unique_together": {
                    ("agency", "pipeline_type", "order"),
                    ("agency", "pipeline_type", "value"),
                },
            },
        ),
    ]
