# Generated by Django 5.2.17 on 2026-09-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agencies", "0012_agencypipelinestage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agencypipelinestage",
            name="value",
            field=models.SlugField(max_length=30, verbose_name="مقدار ذخیره\u200cشده"),
        ),
    ]
