# Generated by Django 5.2.17 on 2026-09-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agencies", "0013_alter_agencypipelinestage_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agencypipelinestage",
            name="pipeline_type",
            field=models.CharField(
                choices=[
                    ("patient", "کاریز خدمت\u200cگیرنده"),
                    ("caregiver", "کاریز خدمت\u200cدهنده"),
                    ("episodic", "کاریز خدمات مقطعی"),
                ],
                max_length=10,
                verbose_name="نوع کاریز",
            ),
        ),
    ]
