// قومیت / زبان مادری و «اهل کجا» — کپی از پنل آژانس (wizard-constants) و backend/apps/caregivers/choices.py؛ هم‌گام نگه دارید.
type Choice = [string, string]

export const ETHNICITY: Choice[] = [
  ["fars", "فارس"],
  ["turk", "آذری/ترک"],
  ["kurd", "کرد"],
  ["lor", "لر"],
  ["gilak", "گیلک"],
  ["mazandarani", "مازندرانی"],
  ["baloch", "بلوچ"],
  ["arab", "عرب"],
  ["turkmen", "ترکمن"],
  ["talesh", "تالشی"],
  ["armenian", "ارمنی"],
  ["qashqai", "قشقایی"],
  ["bakhtiari", "بختیاری"],
  ["other", "سایر"],
]

// زیرگروه (اهل کجا) هر قومیت اصلی — از backend/apps/caregivers/choices.py
// (ETHNICITY_SUBGROUPS) بازنویسی شده؛ هم‌گام نگه دارید.
export const ETHNICITY_SUBGROUPS: Record<string, Choice[]> = {
  fars: [
    ["tehrani", "تهرانی"],
    ["khorasani", "خراسانی"],
    ["isfahani", "اصفهانی"],
    ["shirazi", "شیرازی"],
    ["yazdi", "یزدی"],
    ["kermani", "کرمانی"],
    ["qomi", "قمی"],
    ["kashani", "کاشانی"],
    ["other", "سایر"],
  ],
  turk: [
    ["tabrizi", "تبریزی"],
    ["ardabili", "اردبیلی"],
    ["urmiaei", "ارومیه‌ای"],
    ["zanjani", "زنجانی"],
    ["qazvini", "قزوینی"],
    ["hamedani", "همدانی"],
    ["maraghei", "مراغه‌ای"],
    ["khoyi", "خویی"],
    ["mianei", "میانه‌ای"],
    ["other", "سایر"],
  ],
  kurd: [
    ["sanandaji", "سنندجی"],
    ["kermanshahi", "کرمانشاهی"],
    ["marivani", "مریوانی"],
    ["saqqezi", "سقزی"],
    ["baneh", "بانه‌ای"],
    ["mahabadi", "مهابادی"],
    ["ilami", "ایلامی"],
    ["other", "سایر"],
  ],
  lor: [
    ["lorestani", "لرستانی"],
    ["khorramabadi", "خرم‌آبادی"],
    ["boroujerdi", "بروجردی"],
    ["lak", "لک"],
    ["bakhtiari", "بختیاری"],
    ["mamasani", "ممسنی"],
    ["other", "سایر"],
  ],
  gilak: [
    ["rashti", "رشتی"],
    ["lahijani", "لاهیجانی"],
    ["fomani", "فومنی"],
    ["roudsari", "رودسری"],
    ["anzali", "انزلی‌ای"],
    ["other", "سایر"],
  ],
  mazandarani: [
    ["sari", "ساروی"],
    ["babol", "بابلی"],
    ["amol", "آملی"],
    ["ghaemshahr", "قائمشهری"],
    ["nowshahr", "نوشهری"],
    ["chalus", "چالوسی"],
    ["other", "سایر"],
  ],
  baloch: [
    ["zahedani", "زاهدانی"],
    ["saravani", "سراوانی"],
    ["chabahari", "چابهاری"],
    ["iranshahri", "ایرانشهری"],
    ["nikshahri", "نیکشهری"],
    ["other", "سایر"],
  ],
  arab: [
    ["ahvazi", "اهوازی"],
    ["abadani", "آبادانی"],
    ["khorramshahri", "خرمشهری"],
    ["shadegani", "شادگانی"],
    ["dezful_shushtar_arab", "دزفولی/شوشتریِ عرب‌مجاور"],
    ["other", "سایر"],
  ],
  turkmen: [
    ["gonbad", "گنبدی"],
    ["bandar_turkmen", "بندرترکمن"],
    ["aqqala", "آق‌قلا"],
    ["kalaleh", "کلاله"],
    ["other", "سایر"],
  ],
  talesh: [
    ["talesh_north", "تالش شمالی"],
    ["asalem", "اسالم"],
    ["masal", "ماسال"],
    ["surrounding_areas", "مناطق اطراف"],
    ["other", "سایر"],
  ],
  armenian: [
    ["tehran", "ارمنی‌های تهران"],
    ["isfahan", "ارمنی‌های اصفهان"],
    ["azerbaijan", "ارمنی‌های آذربایجان"],
    ["other", "سایر"],
  ],
  qashqai: [
    ["shiraz", "شیراز"],
    ["firuzabad", "فیروزآباد"],
    ["kazerun", "کازرون"],
    ["nomadic_rural_fars", "مناطق کوچ‌نشین/روستایی فارس"],
    ["other", "سایر"],
  ],
  bakhtiari: [
    ["chaharmahal", "چهارمحال"],
    ["masjed_soleyman", "مسجدسلیمان"],
    ["izeh", "ایذه"],
    ["lordegan", "لردگان"],
    ["other", "سایر"],
  ],
}
