# Generated by Django 6.1.1 on 2026-09-10 08:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0006_seed_beauty_salon_and_skin_clinic_services'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('medical_license_no', models.CharField(help_text='شماره نظام پزشکی', max_length=50)),
                ('specialty', models.CharField(blank=True, max_length=150)),
                ('bio', models.TextField(blank=True, help_text='شرح خدمات')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/photo/')),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('instagram', models.CharField(blank=True, help_text='آیدی پیج اینستاگرام، بدون @', max_length=100)),
                ('rubika', models.CharField(blank=True, help_text='آیدی روبیکا', max_length=100)),
                ('bale', models.CharField(blank=True, help_text='آیدی بله', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('active', 'فعال'), ('inactive', 'غیرفعال')], default='pending', max_length=20)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(blank=True, help_text='اختیاری - اگر این پزشک به یک مطب هم وصل است', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='independent_doctors', to='clinics.clinic')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پزشک (صفحه مستقل)',
                'verbose_name_plural': 'پزشکان (صفحه مستقل)',
            },
        ),
        migrations.CreateModel(
            name='DoctorAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(editable=False, max_length=12, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('national_id', models.CharField(help_text='کد ملی', max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('disease_type', models.CharField(help_text='نوع بیماری / علت مراجعه', max_length=200)),
                ('requested_date', models.DateField()),
                ('requested_time', models.TimeField()),
                ('id_card_image', models.ImageField(blank=True, null=True, upload_to='doctors/appointments/id_card/')),
                ('prescription_image', models.ImageField(blank=True, null=True, upload_to='doctors/appointments/prescription/')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('confirmed', 'تأیید شده'), ('completed', 'انجام شده'), ('rejected', 'رد شده'), ('cancelled', 'لغو شده توسط بیمار'), ('reschedule_requested', 'درخواست جابه\u200cجایی')], default='pending', max_length=25)),
                ('doctor_note', models.TextField(blank=True)),
                ('reschedule_requested_date', models.DateField(blank=True, null=True)),
                ('reschedule_requested_time', models.TimeField(blank=True, null=True)),
                ('reschedule_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نوبت پزشک',
                'verbose_name_plural': 'نوبت\u200cهای پزشک',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنجشنبه'), (6, 'جمعه')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'بازه در دسترس بودن',
                'verbose_name_plural': 'بازه\u200cهای در دسترس بودن',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='DoctorConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'گفتگو با پزشک',
                'verbose_name_plural': 'گفتگوها با پزشک',
                'unique_together': {('doctor', 'patient')},
            },
        ),
        migrations.CreateModel(
            name='DoctorChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('patient', 'بیمار'), ('doctor', 'پزشک')], max_length=10)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='doctors.doctorconversation')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام\u200cها',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'عکس'), ('video', 'ویدیو')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctors/posts/')),
                ('video', models.FileField(blank=True, null=True, upload_to='doctors/posts/')),
                ('caption', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'پست پزشک',
                'verbose_name_plural': 'پست\u200cهای پزشک',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'ردیف تعرفه',
                'verbose_name_plural': 'لیست تعرفه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='DoctorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctorappointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نظر برای پزشک',
                'verbose_name_plural': 'نظرات برای پزشک',
                'ordering': ['-created_at'],
                'unique_together': {('doctor', 'patient', 'appointment')},
            },
        ),
    ]
