# Generated by Django 6.0.6 on 2026-07-05 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0, help_text='موجودی انبار')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, help_text='emoji یا کلاس آیکون', max_length=10)),
            ],
            options={
                'verbose_name': 'نوع فروشگاه',
                'verbose_name_plural': 'انواع فروشگاه',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تأیید فروشگاه'), ('confirmed', 'تأیید و در حال آماده\u200cسازی'), ('completed', 'تحویل داده شد'), ('rejected', 'رد شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('online', 'آنلاین (از کیف پول)'), ('on_site', 'حضوری (پرداخت در محل)')], default='online', max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('address', models.TextField(blank=True, help_text='آدرس تحویل - در صورت خالی، تحویل حضوری در فروشگاه')),
                ('store_note', models.TextField(blank=True, help_text='یادداشت فروشگاه برای مشتری')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='نام محصول در لحظه خرید', max_length=200)),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stores.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='stores.product')),
            ],
            options={
                'verbose_name': 'قلم سفارش',
                'verbose_name_plural': 'اقلام سفارش',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('active', 'فعال'), ('inactive', 'غیرفعال')], default='pending', max_length=20)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='stores/logo/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='stores/cover/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=20.0, help_text='درصد سهم پلتفرم از هر خرید از این فروشگاه', max_digits=5)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL)),
                ('referred_by_marketer', models.ForeignKey(blank=True, help_text='بازاریابی که این فروشگاه را به پلتفرم معرفی کرده (کمیسیون دائمی از فروش این فروشگاه می\u200cگیرد)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_stores', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.storecategory')),
            ],
            options={
                'verbose_name': 'فروشگاه',
                'verbose_name_plural': 'فروشگاه\u200cها',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stores.store'),
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='stores.store'),
        ),
    ]
