# Generated by Django 6.0.7 on 2026-08-10 13:06

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caregivers', '0003_caregiverprofile_created_by'),
        ('families', '0005_access_codes_and_link_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('ended', 'پایان\u200cیافته')], default='active', max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('assigned_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان تخصیص')),
                ('ended_at', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='تخصیص\u200cدهنده')),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='caregivers.caregiverprofile', verbose_name='مراقب')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='families.patientprofile', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'تخصیص مراقب',
                'verbose_name_plural': 'تخصیص\u200cهای مراقب',
                'ordering': ['-assigned_at'],
                'unique_together': {('caregiver', 'patient', 'status')},
            },
        ),
        migrations.CreateModel(
            name='CareLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general', 'یادداشت عمومی'), ('medication', 'دارو'), ('meal', 'تغذیه'), ('mobility', 'تحرک و جابجایی'), ('vitals', 'علائم حیاتی'), ('incident', 'حادثه یا نگرانی')], default='general', max_length=20, verbose_name='دسته')),
                ('note', models.TextField(verbose_name='گزارش')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='care.caregiverassignment', verbose_name='تخصیص')),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_log_entries', to='caregivers.caregiverprofile', verbose_name='مراقب')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_log_entries', to='families.patientprofile', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'گزارش مراقبت',
                'verbose_name_plural': 'گزارش\u200cهای مراقبت',
                'ordering': ['-created_at'],
            },
        ),
    ]
