# Generated by Django 6.0.7 on 2026-08-13 07:43

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0001_initial'),
        ('caregivers', '0004_alter_identityprofile_military_status'),
        ('families', '0007_patientprofile_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='از ۱ (ضعیف) تا ۵ (عالی)', verbose_name='امتیاز')),
                ('comment', models.TextField(blank=True, verbose_name='نظر')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='care.caregiverassignment', verbose_name='تخصیص')),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='caregivers.caregiverprofile', verbose_name='مراقب')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='families.patientprofile', verbose_name='بیمار')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caregiver_reviews_written', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده نظر')),
            ],
            options={
                'verbose_name': 'نظر درباره مراقب',
                'verbose_name_plural': 'نظرات درباره مراقبان',
                'ordering': ['-created_at'],
                'unique_together': {('assignment', 'reviewer')},
            },
        ),
    ]
