# Generated by Django 6.0.7 on 2026-08-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0002_caregiverreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTraitMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[('patient', 'بیمار'), ('caregiver', 'مراقب')], max_length=10, verbose_name='نوع پروفایل')),
                ('question_field', models.CharField(max_length=100, verbose_name='فیلد سؤال')),
                ('answer_option', models.CharField(max_length=30, verbose_name='گزینه پاسخ')),
                ('trait', models.CharField(choices=[('religious_flexibility', 'انعطاف مذهبی'), ('gender_sensitivity', 'حساسیت جنسیتی'), ('ritual_flexibility', 'انعطاف مناسکی'), ('traditional_belief_tolerance', 'تحمل باور سنتی'), ('professional_boundary', 'مرز حرفه\u200cای'), ('privacy_orientation', 'جهت\u200cگیری حریم خصوصی'), ('gender_role_flexibility', 'انعطاف نقش جنسیتی'), ('emotional_involvement', 'درگیری عاطفی'), ('environment_tolerance', 'تحمل محیط'), ('schedule_flexibility', 'انعطاف زمان\u200cبندی'), ('traditional_medicine_orientation', 'جهت\u200cگیری طب سنتی'), ('emotional_interaction_preference', 'ترجیح تعامل عاطفی'), ('orderliness_tolerance', 'تحمل نظم'), ('cultural_tolerance', 'تحمل فرهنگی'), ('offensive_speech_tolerance', 'تحمل گفتار ناخوشایند'), ('ritual_tolerance', 'تحمل آیینی'), ('language_dialect_flexibility', 'انعطاف زبان و گویش')], max_length=50, verbose_name='ویژگی')),
                ('value', models.PositiveSmallIntegerField(verbose_name='مقدار (۰ تا ۱۰۰)')),
            ],
            options={
                'verbose_name': 'نگاشت سؤال به ویژگی',
                'verbose_name_plural': 'نگاشت\u200cهای سؤال به ویژگی',
                'unique_together': {('profile_type', 'question_field', 'answer_option', 'trait')},
            },
        ),
    ]
