# Generated by Django 6.0.7 on 2026-08-23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('care', '0003_questiontraitmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCDMWeightConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pairwise_matrix', models.JSONField(help_text='ماتریس ۶×۶ برای معیارهای: objective_fit, cultural_ritual, values_professional, lifestyle, cultural_flexibility, reputation', verbose_name='ماتریس مقایسه زوجی')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
            ],
            options={
                'verbose_name': 'پیکربندی وزن\u200cهای تطابق',
                'verbose_name_plural': 'پیکربندی\u200cهای وزن\u200cهای تطابق',
                'ordering': ['-updated_at'],
            },
        ),
    ]
