# Generated by Django 5.2.17 on 2026-09-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("care", "0004_mcdmweightconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="caregiverassignment",
            name="billing_cycle",
            field=models.CharField(
                blank=True,
                choices=[
                    ("daily", "روزانه"),
                    ("weekly", "هفتگی"),
                    ("monthly", "ماهانه"),
                ],
                help_text="دوره\u200cای که این تخصیص بر آن اساس صورت\u200cحساب می\u200cشود — یک نسخه محلی از apps.finance.BillingCycle، عمداً کپی\u200cشده تا care به finance وابسته نشود.",
                max_length=10,
                verbose_name="دوره صورت\u200cحساب",
            ),
        ),
        migrations.AddField(
            model_name="caregiverassignment",
            name="custom_daily_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=12,
                null=True,
                verbose_name="نرخ روزانه اختصاصی (تومان)",
            ),
        ),
        migrations.AddField(
            model_name="caregiverassignment",
            name="custom_hourly_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="در صورت خالی بودن، نرخ پیش\u200cفرض تعرفه آژانس برای این نوع خدمت اعمال می\u200cشود.",
                max_digits=12,
                null=True,
                verbose_name="نرخ ساعتی اختصاصی (تومان)",
            ),
        ),
        migrations.AddField(
            model_name="caregiverassignment",
            name="custom_monthly_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=12,
                null=True,
                verbose_name="نرخ ماهانه اختصاصی (تومان)",
            ),
        ),
        migrations.AddField(
            model_name="caregiverassignment",
            name="service_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("daily", "مراقبت روزانه"),
                    ("night", "مراقبت شبانه"),
                    ("live_in", "مراقبت شبانه\u200cروزی (مقیم)"),
                    ("hospital_companion", "همراه سالمند در بیمارستان"),
                    ("home_companion", "همراه سالمند در منزل"),
                    ("short_term", "مراقبت موقت (چند روزه)"),
                    ("long_term", "مراقبت بلندمدت"),
                ],
                help_text="برای تعیین اینکه کدام ردیف تعرفه آژانس (ServiceTariff) روی این تخصیص اعمال شود — خالی یعنی این تخصیص هنوز صورت\u200cحساب نمی\u200cشود.",
                max_length=30,
                verbose_name="نوع خدمت",
            ),
        ),
    ]
